/* TODO(adel): every string here is waiting for your review. */
import type { BuilderCopy } from "./fr";

export const en: BuilderCopy = {
  nav: "Build my software",

  landing: {
    title: "Build the software for your shop",
    intro:
      "Answer a few questions about your shop. You leave with your software, ready to install on the shop computer.",
    duration: "10 to 20 minutes",
    noAccount: "No account needed to start",
    steps: [
      "Your shop, your name and your logo",
      "A few questions about how you work",
      "Your products and staff, if you have them to hand",
      "Your serial number and the download",
    ],
    start: "Start",
    resume: "Pick up where you left off",
  },

  shell: {
    stepOf: "Step {current} of {total}",
    back: "Back",
    next: "Continue",
    preview: "See my software",
    previewTitle: "Your software",
    previewEmpty:
      "Your receipt and sale screen will appear here as soon as you answer.",
    close: "Close",
    help: "Help on WhatsApp",
    helpMessage: "Hello, I need help at step {step} ({name}).",
    saved: "Your answers are saved",
    offline: "Offline. Your answers will be sent when the network is back.",
  },

  steps: {
    business: "Your shop",
    questions: "Questions",
    products: "Products and staff",
    serial: "Your serial number",
  },

  packs: {
    heading: "What kind of business do you run?",
    pharmacy: "Pharmacy",
    bakery: "Bakery",
    restaurant: "Restaurant or cafe",
    warehouse: "Warehouse and stock",
    shop: "Shop or grocery",
    hotel: "Hotel or guest house",
    transport: "Passenger and parcel transport",
    general: "Any other business: sales, stock and reports",
    soon: "Coming soon",
    other: "My business is not on this list",
  },

  lead: {
    heading: "Tell us what you do",
    business: "Your business",
    businessHelp: "For example: hardware shop, hair salon, workshop.",
    phone: "Your phone number",
    submit: "Send",
    thanks: "Thank you. We will tell you as soon as your kind of business is ready.",
    soonHeading: "{trade}: coming soon",
    soonIntro: "This software is not open yet. Leave your number and we will tell you when it is ready.",
    error: "Your message did not go through. Try again, or write to us on WhatsApp.",
  },


  name: {
    heading: "Your business name",
    latin: "In Latin letters",
    latinHelp: "This is the name at the top of the receipt.",
    arabic: "In Arabic, if you want",
    arabicHelp: "It goes under the first name on the receipt.",
    required: "Write your business name to continue.",
  },

  receiptDetails: {
    heading: "What appears on the receipt",
    help: "Both are optional. You can change them later.",
    phone: "Your phone",
    address: "Your address",
  },

  logo: {
    heading: "Your logo",
    help: "Optional. Take a photo or choose a file. It stays on your phone; only the prepared image is sent.",
    choose: "Choose an image",
    replace: "Change the image",
    remove: "Remove the logo",
    working: "Preparing your logo",
    colour: "On the screen",
    mono: "On the printed receipt",
    errorType: "Choose a PNG, JPG or SVG image.",
    errorUnreadable: "This image could not be read. Try another one.",
    errorTooBig: "This image is too heavy even after preparing. Try another one.",
  },

  preview: {
    live: "Live",
    expand: "Enlarge",
    shrink: "Make smaller",
    hint: "This is your software itself: tap the products and buttons, everything works. The products and figures are examples.",
    updated: "Updated: {section}",
    rotate: "Turn your phone sideways to see the screen larger.",
    actualSize: "Actual size",
    fitSize: "See it all",
    loading: "Opening your software",
  },

  save: {
    saving: "Saving",
    saved: "Saved",
    failed: "Not saved yet. We are trying again.",
    unavailable: "Your answers are staying on this device for now.",
  },

  interview: {
    dontKnow: "I do not know",
    explain: "Say it in my own words",
    explainHelp: "Say it the way you would explain it to a new member of staff.",
    send: "Send",
    sending: "One moment",
    noted: "That is not available yet. We have written it down.",
    yes: "Yes",
    no: "No",
    questionOf: "Question {current} of {total}",
  },

  summary: {
    heading: "Check this before you carry on",
    intro: "Here is what your software will do. You can change any of it later.",
    edit: "Change",
    business: "Your business",
    answers: "Your answers",
  },

  products: {
    heading: "Your products",
    help: "Optional. You can add them later in the software.",
    template: "Download the template",
    choose: "Choose my file",
    reading: "Reading your file",
    ready: {
      one: "{count} product ready.",
      other: "{count} products ready.",
    },
    toFix: {
      one: "{count} row to fix.",
      other: "{count} rows to fix.",
    },
    problem: "Row {row}: {what} Check the {column} column.",
    missingName: "name missing.",
    missingPrice: "price missing.",
    badPrice: "price could not be read.",
    badQuantity: "quantity could not be read.",
    badExpiry: "expiry date could not be read.",
    missingColumns: "We could not find the name and price columns. Use the template, or rename your columns.",
    truncated: "Only the first 10,000 rows were read.",
    keep: "Keep these products",
    skip: "Skip this step",
    zeroPrice: "price is zero.",
    negativePrice: "price is negative.",
    pastExpiry: "Row {row}: the expiry date has already passed ({found}). Check it, or import anyway.",
    headerFound: "We found your columns on row {row}.",
    totalsSkipped: "{count} total row skipped.",
    totalsSkippedOther: "{count} total rows skipped.",
    whichSheet: "Which sheet holds your products?",
    sheetRows: "{count} rows",
    whichColumn: "Which column holds {what}?",
    columnName: "the product name",
    columnPrice: "the price",
    columnQuantity: "the quantity",
    columnExpiry: "the expiry date",
    columnBatch: "the batch number",
    noColumn: "None",
    preview: "Here are your first five products, as they will be imported.",
    confirm: "Looks right, import",
    currencyQuestion: "Are your prices in new ouguiyas (MRU) or old ouguiyas?",
    currencyNew: "New ouguiyas (MRU)",
    currencyOld: "Old ouguiyas",
    currencyCheck: "In old ouguiyas, these prices become:",
    duplicates: "These products appear twice.",
    keepFirst: "Keep only one",
    keepAll: "They are two different products",
    mergeQuantities: "Add the quantities together",
    fixRow: "Fix",
    unreadable: "We could not read that file. Send an Excel or CSV file, not a photo or a PDF, and without a password. You can also start from our template.",
    another: "Choose another file",
  },

  staff: {
    heading: "Your staff",
    help: "Optional. Each person's code is chosen later, in the software.",
    name: "Name",
    role: "Role",
    manager: "Manager",
    cashier: "Cashier",
    add: "Add",
    remove: "Remove",
    empty: "Nobody yet.",
  },

  account: {
    heading: "Create your account",
    intro: "So you can find your software and your serial number from any phone.",
    phone: "Your phone number",
    password: "Your password",
    passwordHelp: "At least eight characters.",
    terms: "I accept the terms of use",
    termsLink: "Read the terms",
    create: "Create my account",
    creating: "One moment",
    errorPhone: "Write a valid phone number.",
    errorPassword: "Your password must be at least eight characters.",
    errorTerms: "Accept the terms to carry on.",
    errorTaken: "This number already has an account.",
    errorGeneric: "Your account could not be created. Try again, or write to us on WhatsApp.",
  },

  serial: {
    heading: "Your serial number",
    intro: "Keep it. You will need it to install your software on the shop computer.",
    copy: "Copy",
    copied: "Copied",
    share: "Share on WhatsApp",
    shareMessage: "My serial number: {serial}. Download: {url}",
    windows: "Download for Windows",
    mac: "Download for Mac",
    macApple: "Download for Mac with Apple chip",
    macIntel: "Download for Mac with Intel chip",
    otherMacApple: "Does your Mac have an Apple chip (M1 or newer)? Download that version",
    otherMacIntel: "Does your Mac have an Intel chip? Download that version",
    soon: "The software to install will be available soon. Keep your serial number.",
    onPhone: "To install it, open this address on the shop computer:",
    tutorialWindows: "Watch the Windows installation video",
    tutorialMac: "Watch the Mac installation video",

    pcHeading: "Your software is ready",
    downloadInstall: "Download and install",
    alsoMac: "On a Mac? Download for Mac",
    alsoWindows: "On Windows? Download for Windows",
    keepNumber: "Keep this number: you will need it for a second computer or a reinstall.",
    windowsWarning:
      "Windows may show \"Windows protected your PC\". Click \"More info\", then \"Run anyway\".",
    macWarning: "Open the file, drag OUAQT into Applications, then right-click OUAQT and choose \"Open\".",
    macWarningStill: "If the Mac still refuses to open it: open System Settings, then Privacy & Security, and click \"Open Anyway\".",
    onMac: "On a Mac",
    onWindows: "On Windows",
    afterInstall: "Once the software is installed:",
    open: "Open my software",
    opening: "Opening…",
    macOpenFirst: "On a Mac, open the software once from Applications first, then press this button.",
    openFallback: "If nothing opens, type your serial number into the software: it will ask for it.",
    openFailed: "The link could not be prepared. Type your serial number into the software.",
  },

  install: {
    question: "Which computer will you install your software on?",
    windows: "Windows",
    windowsHint: "Desktop or laptop",
    macIntel: "Mac with Intel chip",
    macIntelHint: "Most Macs from before 2021",
    macApple: "Mac with Apple chip",
    macAppleHint: "M1, M2, M3 or newer",
    detected: "This computer",
    whichMac: "Intel or Apple chip? Apple menu, then \"About This Mac\": the \"Chip\" or \"Processor\" line tells you.",
    downloadWindows: "Download for Windows",
    downloadMacIntel: "Download for Mac with Intel chip",
    downloadMacApple: "Download for Mac with Apple chip",
    guideWindows: "Installing on Windows",
    guideMac: "Installing on a Mac",
    guideIntro: "A few minutes. Windows and the Mac warn about any software they do not know yet: that is normal, and here is what to do.",
    once: "These warnings only appear the first time you install.",
    winStep1Title: "Open the downloaded file",
    winStep1: "It is called OUAQT-windows-setup.exe. You will find it in your Downloads.",
    winStep2Title: "Blue screen: \"More info\"",
    winStep2: "Windows shows \"Windows protected your PC\". Click \"More info\".",
    winStep3Title: "Then \"Run anyway\"",
    winStep3: "The button appears at the bottom. The installation then runs by itself.",
    winStep4Title: "Open OUAQT",
    winStep4: "The OUAQT icon appears on the desktop. The software opens and asks for your serial number.",
    macStep1Title: "Open the downloaded file",
    macStep1: "Double-click the OUAQT file in your Downloads.",
    macStep2Title: "Drag OUAQT into Applications",
    macStep2: "A window opens: drag the OUAQT icon onto the Applications folder.",
    macStep3Title: "Open OUAQT once",
    macStep3: "In Applications, double-click OUAQT. The Mac shows a warning: click \"Done\".",
    macStep4Title: "Privacy & Security: \"Open Anyway\"",
    macStep4: "Open System Settings (Apple menu), then Privacy & Security. At the bottom, next to \"OUAQT was blocked\", click \"Open Anyway\".",
    macStep5Title: "Confirm once",
    macStep5: "The Mac asks for your password, then click \"Open\". From then on, OUAQT opens normally, every time.",
    lastTitle: "Activate with your number",
    last: "Type your serial number into OUAQT, or press \"Open my software\" on this page. Your free trial starts.",
    artDownloads: "Downloads",
    artWinTitle: "Windows protected your PC",
    artWinBody: "Microsoft Defender SmartScreen prevented an unrecognised app from starting.",
    artMoreInfo: "More info",
    artApp: "App",
    artRunAnyway: "Run anyway",
    artDontRun: "Don't run",
    artApplications: "Applications",
    artMacTitle: "\"OUAQT\" Not Opened",
    artMacBody: "Apple could not verify \"OUAQT\" is free of malware.",
    artTrash: "Move to Trash",
    artDone: "Done",
    artPrivacy: "Privacy & Security",
    artGeneral: "General",
    artBlocked: "\"OUAQT\" was blocked to protect your Mac.",
    artOpenAnyway: "Open Anyway",
    artOpen: "Open",
    artPassword: "Password",
    artSerial: "Your serial number",
    artValidate: "Confirm",
  },

  myAccount: {
    title: "My account",
    signInHeading: "Open my account",
    signIn: "Open my account",
    signOut: "Sign out",
    signInError: "Wrong number or password.",
    mySoftware: "My software",
    mySubscription: "My subscription",
    myDevices: "My computers",
    myRequests: "My requests",
    edit: "Change my software",
    noBusiness: "You have not built your software yet.",
    start: "Build my software",
    soon: "This part is coming soon. Write to us on WhatsApp if you need anything.",
    noRequests: "No requests yet.",
  },

  licence: {
    notStarted: "Your trial will start when you install the software on the shop computer.",
    trial: {
      one: "Free trial, {count} day left.",
      other: "Free trial, {count} days left.",
    },
    trialOver: "Your trial has ended. The software keeps everything you recorded but takes no new sales. Once you pay, everything opens again.",
    active: "Licence active until {date}.",
    renewalDue: {
      one: "Your licence has ended. You have {count} day before the software becomes read only.",
      other: "Your licence has ended. You have {count} days before the software becomes read only.",
    },
    expired: "Your licence has ended. The software keeps everything you recorded but takes no new sales. Once you pay, everything opens again.",
    suspended: "Your licence is suspended. Write to us on WhatsApp.",
    pending: "Payment received, being checked. As soon as it is confirmed, your software works normally, with nothing for you to do.",
    rejected: "Your last payment could not be accepted.",
  },

  pay: {
    heading: "Pay for my licence",
    amount: "Amount to pay",
    perMonth: "that is {amount} a month",
    duration: "Pay for",
    year: "1 year",
    sixMonths: "6 months",
    wasPrice: "Usual price",
    chooseApp: "Which app are you paying with?",
    number: "OUAQT's {app} number",
    copyNumber: "Copy the number",
    copied: "Copied",
    step1: "Send the amount from {app} to the number above.",
    step2: "Send the screenshot of the confirmation here.",
    screenshot: "The screenshot",
    choose: "Choose the screenshot",
    replace: "Change the screenshot",
    screenshotAlt: "The screenshot you chose",
    send: "Send my payment",
    checking: "Checking the payment",
    checkingNote: "We are checking your screenshot. It takes a few seconds.",
    successTitle: "Payment successful. Thank you.",
    receivedTitle: "Payment received",
    receivedBody: "We are checking it, usually within the day. As soon as it is confirmed, your software works normally, with nothing for you to do.",
    problemTitle: "The payment did not go through",
    problemHelp: "Send a new screenshot, or write to us on WhatsApp.",
    soonPrice: "Price available soon.",
    noNumber: "Paying by app will be available soon. Write to us on WhatsApp in the meantime.",
    errorImage: "Choose the image of the confirmation.",
    errorSend: "It did not go through. Try again, or write to us on WhatsApp.",
    failReferenceUsed: "That transaction number has already been sent to us.",
    failImageUsed: "That screenshot has already been sent to us.",
    failNotReceipt: "That image does not look like a transfer confirmation. Choose the screenshot of the confirmation.",
    failAmount: "The amount on the screenshot is {found} MRU. The amount for this plan is {expected} MRU.",
    failAmountUnread: "The amount does not show on the screenshot. It should be {expected} MRU.",
    failRecipient: "The payment did not go to OUAQT's number ({expected}).",
    failRecipientUnread: "The recipient's number does not show on the screenshot. It should be {expected}.",
    failDate: "The screenshot is from {found}, not today. Send the screenshot of a payment made today.",
    failDateUnread: "The date does not show on the screenshot.",
    confirmedNow: "Your licence is active. Your software opens again by itself within a minute, if it is open and connected to the internet.",
    readTitle: "Read on your screenshot",
    readAmount: "Amount",
    readDate: "Date",
    readReference: "Transaction",
  },

  devices: {
    none: "No computer yet. Yours appears here as soon as you install the software.",
    main: "Main computer",
    secondary: "Second computer",
    lastSeen: "Seen on {date}",
    release: "This computer no longer works",
    confirm: "Free this computer? You will be able to install the software on another one.",
    cancel: "No, keep it",
    releasing: "One moment",
    released: "Freed. You can install the software on another computer.",
    tooMany: "You have already freed all the computers allowed this year. Write to us on WhatsApp and we will do it for you.",
    failed: "Not freed. Try again, or write to us on WhatsApp.",
  },

  code: {
    have: "I already have my serial number",
    label: "Your serial number",
    placeholder: "XXXX-XXXX",
    open: "Continue",
    opening: "One moment…",
    unknown: "Number not found. Check the characters, or ask for it to be sent again.",
    expired: "This number has expired. You can start the configuration again, or write to us on WhatsApp.",
    restart: "Start again",
    contact: "Write on WhatsApp",
    expiredMessage: "Hello, my serial number has expired: {code}",
    wait: "Too many tries. Try again in {seconds} s.",
    failed: "The number could not be checked. Try again in a moment.",
    lost: "Lost your number?",
    lostIntro: "Type the phone number you gave during the configuration. Your serial number will be sent to you again on WhatsApp.",
    lostPhone: "Phone number",
    lostSend: "Send",
    lostDone: "Noted. If this phone was used for a configuration, you will receive the serial number on WhatsApp.",
    issuedHeading: "Your serial number",
    issuedIntro: "You are done on the phone. On the shop computer, open the OUAQT website and type this number: your software is ready to download.",
    issuedSent: "It was also sent to you on WhatsApp.",
    issuedKeep: "Take a screenshot of this number, or write it on paper.",
    issuedPhone: "Your WhatsApp number, so it can be sent to you again",
    issuedPhoneSave: "Save",
    issuedPhoneSaved: "WhatsApp number saved.",
    issuedContinue: "Continue on this phone",
    copy: "Copy",
    copied: "Copied",
    switched: "The page has switched to {language}, the language of your configuration.",
    switchBack: "Back to {language}",
    retry: "Try again",
    preparing: "Preparing your software…",
    downloadFailed: "The software could not be prepared. Try again, or write to us on WhatsApp.",
    downloadIntro: "Free trial of {days} days. After the trial, you pay on this site with this same number.",
  },

  payBySerial: {
    title: "Pay my subscription",
    heading: "Pay with your serial number",
    intro: "Type your software's serial number. No account needed.",
    link: "Pay with my serial number",
  },

  placeholder: {
    title: "This step is coming soon",
    body: "We are preparing the questions for this step. Come back in a few days, or write to us on WhatsApp.",
  },
};
