/* TODO(adel): every string here is waiting for your review. */
import type { BuilderCopy } from "./fr";

export const en: BuilderCopy = {
  nav: "Build my software",

  landing: {
    title: "Build the software for your shop",
    intro:
      "Answer a few questions about your shop. You leave with your software, ready to install on the shop computer.",
    duration: "10 to 20 minutes",
    noAccount: "No account needed to start",
    steps: [
      "Your shop, your name and your logo",
      "A few questions about how you work",
      "Your products and staff, if you have them to hand",
      "Your serial number and the download",
    ],
    start: "Start",
    resume: "Pick up where you left off",
  },

  shell: {
    stepOf: "Step {current} of {total}",
    back: "Back",
    next: "Continue",
    preview: "See my software",
    previewTitle: "Your software",
    previewEmpty:
      "Your receipt and sale screen will appear here as soon as you answer.",
    close: "Close",
    help: "Help on WhatsApp",
    helpMessage: "Hello, I need help at step {step} ({name}).",
    saved: "Your answers are saved",
    offline: "Offline. Your answers will be sent when the network is back.",
  },

  steps: {
    business: "Your shop",
    questions: "Questions",
    products: "Products and staff",
    serial: "Your serial number",
  },

  packs: {
    heading: "What kind of business do you run?",
    pharmacy: "Pharmacy",
    bakery: "Bakery",
    restaurant: "Restaurant or cafe",
    warehouse: "Warehouse and stock",
    shop: "Shop or grocery",
    hotel: "Hotel or guest house",
    transport: "Passenger and parcel transport",
    general: "Any other business: sales, stock and reports",
    soon: "Coming soon",
    other: "My business is not on this list",
  },

  lead: {
    heading: "Tell us what you do",
    business: "Your business",
    businessHelp: "For example: hardware shop, hair salon, workshop.",
    phone: "Your phone number",
    submit: "Send",
    thanks: "Thank you. We will tell you as soon as your kind of business is ready.",
    error: "Your message did not go through. Try again, or write to us on WhatsApp.",
  },

  language: {
    heading: "Which language would you like to answer in?",
    appHeading: "And which language will your staff use the software in?",
    fr: "Français",
    ar: "العربية",
    en: "English",
  },

  name: {
    heading: "Your business name",
    latin: "In Latin letters",
    latinHelp: "This is the name at the top of the receipt.",
    arabic: "In Arabic, if you want",
    arabicHelp: "It goes under the first name on the receipt.",
    required: "Write your business name to continue.",
  },

  receiptDetails: {
    heading: "What appears on the receipt",
    help: "Both are optional. You can change them later.",
    phone: "Your phone",
    address: "Your address",
  },

  logo: {
    heading: "Your logo",
    help: "Optional. Take a photo or choose a file. It stays on your phone; only the prepared image is sent.",
    choose: "Choose an image",
    replace: "Change the image",
    remove: "Remove the logo",
    working: "Preparing your logo",
    colour: "On the screen",
    mono: "On the printed receipt",
    errorType: "Choose a PNG or JPEG image.",
    errorUnreadable: "This image could not be read. Try another one.",
    errorTooBig: "This image is too heavy even after preparing. Try another one.",
  },

  preview: {
    sale: "Sale screen",
    receipt: "Receipt",
    intro: "Here is your software with what you have just written.",
    tables: "Tables",
    kitchen: "Kitchen ticket",
    production: "Production",
    moves: "Goods in and out",
  },

  save: {
    saving: "Saving",
    saved: "Saved",
    failed: "Not saved yet. We are trying again.",
    unavailable: "Your answers are staying on this device for now.",
  },

  interview: {
    dontKnow: "I do not know",
    explain: "Say it in my own words",
    explainHelp: "Say it the way you would explain it to a new member of staff.",
    send: "Send",
    sending: "One moment",
    noted: "That is not available yet. We have written it down.",
    yes: "Yes",
    no: "No",
    questionOf: "Question {current} of {total}",
  },

  summary: {
    heading: "Check this before you carry on",
    intro: "Here is what your software will do. You can change any of it later.",
    edit: "Change",
    business: "Your business",
    answers: "Your answers",
  },

  products: {
    heading: "Your products",
    help: "Optional. You can add them later in the software.",
    template: "Download the template",
    choose: "Choose my file",
    reading: "Reading your file",
    ready: {
      one: "{count} product ready.",
      other: "{count} products ready.",
    },
    toFix: {
      one: "{count} row to fix.",
      other: "{count} rows to fix.",
    },
    problem: "Row {row}: {what} Check the {column} column.",
    missingName: "name missing.",
    missingPrice: "price missing.",
    badPrice: "price could not be read.",
    badQuantity: "quantity could not be read.",
    badExpiry: "expiry date could not be read.",
    missingColumns: "We could not find the name and price columns. Use the template, or rename your columns.",
    truncated: "Only the first 10,000 rows were read.",
    keep: "Keep these products",
    skip: "Skip this step",
    zeroPrice: "price is zero.",
    negativePrice: "price is negative.",
    pastExpiry: "Row {row}: the expiry date has already passed ({found}). Check it, or import anyway.",
    headerFound: "We found your columns on row {row}.",
    totalsSkipped: "{count} total row skipped.",
    totalsSkippedOther: "{count} total rows skipped.",
    whichSheet: "Which sheet holds your products?",
    sheetRows: "{count} rows",
    whichColumn: "Which column holds {what}?",
    columnName: "the product name",
    columnPrice: "the price",
    columnQuantity: "the quantity",
    columnExpiry: "the expiry date",
    columnBatch: "the batch number",
    noColumn: "None",
    preview: "Here are your first five products, as they will be imported.",
    confirm: "Looks right, import",
    currencyQuestion: "Are your prices in new ouguiyas (MRU) or old ouguiyas?",
    currencyNew: "New ouguiyas (MRU)",
    currencyOld: "Old ouguiyas",
    currencyCheck: "In old ouguiyas, these prices become:",
    duplicates: "These products appear twice.",
    keepFirst: "Keep only one",
    keepAll: "They are two different products",
    mergeQuantities: "Add the quantities together",
    fixRow: "Fix",
    unreadable: "We could not read that file. Send an Excel or CSV file, not a photo or a PDF, and without a password. You can also start from our template.",
    another: "Choose another file",
  },

  staff: {
    heading: "Your staff",
    help: "Optional. Each person's code is chosen later, in the software.",
    name: "Name",
    role: "Role",
    manager: "Manager",
    cashier: "Cashier",
    add: "Add",
    remove: "Remove",
    empty: "Nobody yet.",
  },

  account: {
    heading: "Create your account",
    intro: "So you can find your software and your serial number from any phone.",
    phone: "Your phone number",
    password: "Your password",
    passwordHelp: "At least eight characters.",
    terms: "I accept the terms of use",
    termsLink: "Read the terms",
    create: "Create my account",
    creating: "One moment",
    errorPhone: "Write a valid phone number.",
    errorPassword: "Your password must be at least eight characters.",
    errorTerms: "Accept the terms to carry on.",
    errorTaken: "This number already has an account.",
    errorGeneric: "Your account could not be created. Try again, or write to us on WhatsApp.",
  },

  serial: {
    heading: "Your serial number",
    intro: "Keep it. You will need it to install your software on the shop computer.",
    copy: "Copy",
    copied: "Copied",
    share: "Share on WhatsApp",
    shareMessage: "My serial number: {serial}. Download: {url}",
    windows: "Download for Windows",
    mac: "Download for Mac",
    soon: "The software to install will be available soon. Keep your serial number.",
    onPhone: "To install it, open this address on the shop computer:",
    tutorialWindows: "Watch the Windows installation video",
    tutorialMac: "Watch the Mac installation video",

    pcHeading: "Your software is ready",
    downloadInstall: "Download and install",
    alsoMac: "On a Mac? Download for Mac",
    alsoWindows: "On Windows? Download for Windows",
    keepNumber: "Keep this number: you will need it for a second computer or a reinstall.",
    windowsWarning:
      "Windows may show \"Windows protected your PC\". Click \"More info\", then \"Run anyway\".",
    macWarning: "Open the file, drag OUAQT into Applications, then right-click OUAQT and choose \"Open\".",
    afterInstall: "Once the software is installed:",
    open: "Open my software",
    opening: "Opening…",
    macOpenFirst: "On a Mac, open the software once from Applications first, then press this button.",
    openFallback: "If nothing opens, type your serial number into the software: it will ask for it.",
    openFailed: "The link could not be prepared. Type your serial number into the software.",
  },

  myAccount: {
    title: "My account",
    signInHeading: "Open my account",
    signIn: "Open my account",
    signOut: "Sign out",
    signInError: "Wrong number or password.",
    mySoftware: "My software",
    mySubscription: "My subscription",
    myDevices: "My computers",
    myRequests: "My requests",
    edit: "Change my software",
    noBusiness: "You have not built your software yet.",
    start: "Build my software",
    soon: "This part is coming soon. Write to us on WhatsApp if you need anything.",
    noRequests: "No requests yet.",
  },

  licence: {
    notStarted: "Your trial will start when you install the software on the shop computer.",
    trial: {
      one: "Free trial, {count} day left.",
      other: "Free trial, {count} days left.",
    },
    trialOver: "Your trial has ended. The software keeps everything you recorded but takes no new sales. Paying unlocks it straight away.",
    active: "Licence active until {date}.",
    renewalDue: {
      one: "Your licence has ended. You have {count} day before the software becomes read only.",
      other: "Your licence has ended. You have {count} days before the software becomes read only.",
    },
    expired: "Your licence has ended. The software keeps everything you recorded but takes no new sales. Paying unlocks it straight away.",
    suspended: "Your licence is suspended. Write to us on WhatsApp.",
    pending: "Payment received, being checked. You can carry on using your software.",
    rejected: "Your last payment could not be accepted.",
  },

  pay: {
    heading: "Pay for my licence",
    amount: "Amount to pay",
    perMonth: "that is {amount} a month",
    wasPrice: "Usual price",
    number: "OUAQT's Bankily number",
    copyNumber: "Copy the number",
    copied: "Copied",
    step1: "Send the amount from Bankily to the number above.",
    step2: "Take a screenshot of the confirmation.",
    step3: "Send it here, with the transaction number.",
    screenshot: "The screenshot",
    choose: "Choose the screenshot",
    replace: "Change the screenshot",
    reference: "The transaction number",
    referenceHelp: "It is written on the Bankily confirmation.",
    send: "Send my payment",
    sending: "Sending",
    soonPrice: "Price available soon.",
    noNumber: "Paying by Bankily will be available soon. Write to us on WhatsApp in the meantime.",
    errorImage: "Choose the image of the confirmation.",
    errorReference: "Write the transaction number.",
    errorSend: "It did not go through. Try again, or write to us on WhatsApp.",
    failReferenceUsed: "That transaction number has already been sent to us.",
    failImageUsed: "That screenshot has already been sent to us.",
    failAmount: "The amount on the screenshot is {found} MRU. The amount expected is {expected} MRU. Check the transfer, or write to us.",
    failRecipient: "That transfer did not go to our number.",
    failTooOld: "That transfer is more than {expected} days old. Make a new one, or write to us.",
  },

  devices: {
    none: "No computer yet. Yours appears here as soon as you install the software.",
    main: "Main computer",
    secondary: "Second computer",
    lastSeen: "Seen on {date}",
    release: "This computer no longer works",
    confirm: "Free this computer? You will be able to install the software on another one.",
    cancel: "No, keep it",
    releasing: "One moment",
    released: "Freed. You can install the software on another computer.",
    tooMany: "You have already freed all the computers allowed this year. Write to us on WhatsApp and we will do it for you.",
    failed: "Not freed. Try again, or write to us on WhatsApp.",
  },

  placeholder: {
    title: "This step is coming soon",
    body: "We are preparing the questions for this step. Come back in a few days, or write to us on WhatsApp.",
  },
};
