import type { AppLanguage } from "@/app-ui";

/*
 * The words on the preview's screens, in the language the shop's staff will
 * read every day.
 *
 * They follow the desktop app's own words wherever the app has a screen for
 * them: the sections down the side carry exactly the app's labels, so what
 * the owner learns here is what they will find on the day. French is written
 * first; the other two follow its meaning.
 *
 * "{name}" marks a value filled in on the screen.
 */

export const fr = {
  shopPlaceholder: "Votre commerce",
  nav: {
    sale: "Vente",
    counter: "Commandes",
    overview: "Tableau de bord",
    dashboard: "Accueil",
    menu: "Carte",
    production: "Production",
    preorders: "Commandes",
    moves: "Mouvements",
    rooms: "Chambres",
    stays: "Réservations",
    extras: "Extras",
    trips: "Départs",
    parcels: "Colis",
    network: "Lignes",
    stock: "Stock",
    expenses: "Dépenses",
    customers: "Clients",
    cash: "Caisse",
    reports: "Rapports",
    settings: "Réglages",
  },
  till: {
    searchName: "Nom du produit",
    searchBarcode: "Code-barres",
    searchBoth: "Nom ou code-barres",
    all: "Tout",
    ticket: "Ticket",
    empty: "Touchez un produit pour commencer.",
    total: "Total",
    charge: "Encaisser",
    credit: "À crédit",
    discount: "Remise",
    discountLine: "Remise de 10 %",
    stock: "Stock",
    lowStock: "Stock bas",
    out: "Rupture",
    expires: "Expire le",
    expiresSoon: "Périme bientôt",
    batch: "Lot",
    perKg: "le kg",
    retail: "Boîte ou au détail",
    options: "Options",
    optionsFor: "Options : {name}",
    optionList: "Sans piment|Sans oignon|Fromage en plus",
    add: "Ajouter",
    cancel: "Annuler",
    dineIn: "Sur place",
    takeaway: "À emporter",
    delivery: "Livraison",
    table: "Table",
    chooseTable: "Choisissez la table",
    free: "Libre",
    zone: "Salle",
    sendPrinted: "Envoyer en cuisine",
    sendSpoken: "Noter la commande",
    waiting: "Commandes en attente",
    noneWaiting: "Aucune commande en attente.",
    todayTotal: "Total du jour",
    salesCount: "Ventes",
    ordersCount: "Commandes",
    cashier: "Caissier",
    manager: "Gérant",
    whoOwes: "Qui achète à crédit ?",
    room: "Chambre",
    toRoom: "Mettre sur la chambre",
    chooseRoom: "Sur quelle chambre ?",
    kitchenTicket: "Cuisine",
    overLimit: "Au-delà du plafond",
    owes: "Doit",
  },
  notes: {
    saved: "Vente enregistrée.",
    printed: "Vente enregistrée. Reçu imprimé.",
    credit: "Mis sur le compte de {name}.",
    kitchenPrinted: "Ticket imprimé en cuisine.",
    kitchenSpoken: "Commande notée.",
    roomCharged: "Ajouté à la chambre {name}.",
    checkedIn: "Chambre {name} occupée.",
    seatSold: "Place {name} vendue.",
    ticketSold: "Billet vendu.",
    parcelAdded: "Colis enregistré.",
    moveAdded: "Mouvement enregistré.",
    batchAdded: "Fournée ajoutée.",
    closedDay: "Journée fermée. Le rapport est prêt.",
    closedShift: "Service fermé. Le rapport est prêt.",
    orderAdded: "Commande notée.",
    expenseAdded: "Dépense notée.",
    received: "Réception enregistrée.",
  },
  stock: {
    title: "Stock",
    product: "Produit",
    quantity: "Quantité",
    price: "Prix",
    expiry: "Péremption",
    batch: "Lot",
    supplier: "Fournisseur",
    newProduct: "Nouveau produit",
    receive: "Réception",
    services: "Prestations",
    available: "Disponible",
  },
  customers: {
    title: "Clients",
    name: "Client",
    owes: "Doit",
    limit: "Plafond",
    nothing: "Rien",
    total: "Total des crédits",
    newCustomer: "Nouveau client",
  },
  cash: {
    daily: "Caisse du jour",
    shift: "Caisse du service",
    float: "Fond de caisse",
    cashIn: "Encaissé en espèces",
    creditOut: "Vendu à crédit",
    expected: "Attendu dans le tiroir",
    closeDay: "Fermer la journée",
    closeShift: "Fermer le service",
    closed: "Fermée",
  },
  reports: {
    title: "Rapports",
    today: "Aujourd'hui",
    total: "Chiffre du jour",
    sales: "Ventes",
    average: "Panier moyen",
    best: "Les plus vendus",
    week: "Les sept derniers jours",
    print: "Imprimer sur A4",
    days: "Lun|Mar|Mer|Jeu|Ven|Sam|Dim",
    nothing: "Aucune vente pour l'instant.",
  },
  settings: {
    title: "Réglages",
    shop: "Votre commerce",
    name: "Nom",
    phone: "Téléphone",
    address: "Adresse",
    empty: "Pas encore renseigné",
    printing: "Impression",
    receipts: "Reçus et tickets sur 80 mm",
    documents: "Rapports et documents sur A4",
    noPrinter: "Sans imprimante : chaque vente est enregistrée, sans reçu.",
    computers: "Ordinateurs",
    staff: "Qui encaisse",
    onlyOwner: "Vous seul",
    manager: "Gérant",
    cashier: "Caissier",
    language: "Langue",
  },
  overview: {
    salesToday: "Ventes du jour",
    lowStock: "Produits en stock bas",
    expiring: "Périment dans les {name} mois",
    credit: "Crédits en cours",
    expensesMonth: "Dépenses du mois",
  },
  production: {
    title: "Production du jour",
    made: "Produit",
    sold: "Vendu",
    left: "Reste",
    addBatch: "Fournée",
    loss: "Ce qui reste le soir est compté en perte.",
    resell: "Ce qui reste le soir est revendu le lendemain.",
    untracked: "Ce qui reste le soir n'est pas compté.",
  },
  preorders: {
    title: "Commandes à l'avance",
    customer: "Client",
    order: "Commande",
    due: "Pour",
    deposit: "Avance",
    noDeposit: "Aucune",
    newOrder: "Nouvelle commande",
    today: "Aujourd'hui",
    tomorrow: "Demain",
  },
  moves: {
    title: "Entrées et sorties",
    all: "Tous les lieux",
    in: "Entrée",
    out: "Sortie",
    product: "Produit",
    quantity: "Quantité",
    party: "De ou vers",
    place: "Lieu",
    at: "Heure",
    supplier: "Fournisseur",
    customers: "Client",
    my_shops: "Ma boutique",
    sites: "Chantier",
    piece: "pièces",
    case: "cartons",
    kilo: "kg",
    litre: "litres",
  },
  rooms: {
    title: "Chambres",
    free: "Libre",
    occupied: "Occupée",
    cleaning: "À nettoyer",
    floor: "Étage",
    count: "{name} occupées",
    checkIn: "Arrivée en chambre {name}",
    guest: "Nom du client",
    nights: "Nuits",
    document: "Pièce d'identité",
    advance: "Avance",
    confirm: "Valider l'arrivée",
  },
  stays: {
    title: "Réservations",
    guest: "Client",
    room: "Chambre",
    arrival: "Arrivée",
    nights: "Nuits",
    advance: "Avance",
    balance: "Reste à payer",
    document: "Pièce",
    checked: "Vue",
  },
  trips: {
    title: "Départs du jour",
    seats: "places vendues",
    parcels: "colis",
    chooseSeat: "Touchez une place libre pour vendre le billet.",
    sellTicket: "Vendre un billet",
    full: "Complet",
    driver: "Chauffeur",
  },
  parcels: {
    title: "Colis",
    number: "N°",
    route: "Trajet",
    sender: "Expéditeur",
    receiver: "Destinataire",
    paidAtStart: "Payé au départ",
    payOnArrival: "À payer à l'arrivée",
    newParcel: "Nouveau colis",
  },
  network: {
    title: "Lignes",
    route: "Ligne",
    price: "Billet",
    parcel: "Colis",
    departures: "Départs par jour",
  },
  expenses: {
    title: "Dépenses",
    what: "Dépense",
    amount: "Montant",
    when: "Date",
    newExpense: "Nouvelle dépense",
    month: "Ce mois-ci",
  },
  languages: { fr: "Français", ar: "العربية", en: "English" },
} as const;

type Shape<T> = { readonly [K in keyof T]: T[K] extends string ? string : Shape<T[K]> };
export type Words = Shape<typeof fr>;

export const ar: Words = {
  shopPlaceholder: "متجرك",
  nav: {
    sale: "بيع",
    counter: "الطلبات",
    overview: "لوحة القيادة",
    dashboard: "الرئيسية",
    menu: "القائمة",
    production: "الإنتاج",
    preorders: "الطلبيات",
    moves: "الحركات",
    rooms: "الغرف",
    stays: "الحجوزات",
    extras: "الإضافات",
    trips: "الرحلات",
    parcels: "الطرود",
    network: "الخطوط",
    stock: "المخزون",
    expenses: "المصاريف",
    customers: "الزبائن",
    cash: "الصندوق",
    reports: "التقارير",
    settings: "الإعدادات",
  },
  till: {
    searchName: "اسم المنتج",
    searchBarcode: "الرمز الشريطي",
    searchBoth: "الاسم أو الرمز الشريطي",
    all: "الكل",
    ticket: "التذكرة",
    empty: "اضغط على منتج للبدء.",
    total: "المجموع",
    charge: "تحصيل",
    credit: "بالدين",
    discount: "تخفيض",
    discountLine: "تخفيض 10 %",
    stock: "المخزون",
    lowStock: "مخزون منخفض",
    out: "نفد",
    expires: "ينتهي في",
    expiresSoon: "ينتهي قريبا",
    batch: "الدفعة",
    perKg: "للكيلو",
    retail: "علبة أو بالتجزئة",
    options: "خيارات",
    optionsFor: "خيارات: {name}",
    optionList: "بدون فلفل|بدون بصل|جبن إضافي",
    add: "إضافة",
    cancel: "إلغاء",
    dineIn: "في المطعم",
    takeaway: "سفري",
    delivery: "توصيل",
    table: "طاولة",
    chooseTable: "اختر الطاولة",
    free: "فارغة",
    zone: "القاعة",
    sendPrinted: "إرسال إلى المطبخ",
    sendSpoken: "تسجيل الطلب",
    waiting: "طلبات في الانتظار",
    noneWaiting: "لا طلبات في الانتظار.",
    todayTotal: "مجموع اليوم",
    salesCount: "المبيعات",
    ordersCount: "الطلبات",
    cashier: "أمين الصندوق",
    manager: "المسؤول",
    whoOwes: "من يشتري بالدين؟",
    room: "غرفة",
    toRoom: "على حساب الغرفة",
    chooseRoom: "على أي غرفة؟",
    kitchenTicket: "المطبخ",
    overLimit: "يتجاوز الحد",
    owes: "عليه",
  },
  notes: {
    saved: "تم تسجيل البيع.",
    printed: "تم تسجيل البيع وطباعة الوصل.",
    credit: "أضيف إلى حساب {name}.",
    kitchenPrinted: "طبعت التذكرة في المطبخ.",
    kitchenSpoken: "تم تسجيل الطلب.",
    roomCharged: "أضيف إلى الغرفة {name}.",
    checkedIn: "الغرفة {name} مشغولة.",
    seatSold: "بيع المقعد {name}.",
    ticketSold: "بيعت التذكرة.",
    parcelAdded: "تم تسجيل الطرد.",
    moveAdded: "تم تسجيل الحركة.",
    batchAdded: "أضيفت دفعة جديدة.",
    closedDay: "أغلق اليوم. التقرير جاهز.",
    closedShift: "أغلقت المناوبة. التقرير جاهز.",
    orderAdded: "تم تسجيل الطلبية.",
    expenseAdded: "تم تسجيل المصروف.",
    received: "تم تسجيل الاستلام.",
  },
  stock: {
    title: "المخزون",
    product: "المنتج",
    quantity: "الكمية",
    price: "السعر",
    expiry: "انتهاء الصلاحية",
    batch: "الدفعة",
    supplier: "المورد",
    newProduct: "منتج جديد",
    receive: "استلام",
    services: "الخدمات",
    available: "متوفر",
  },
  customers: {
    title: "الزبائن",
    name: "الزبون",
    owes: "عليه",
    limit: "الحد",
    nothing: "لا شيء",
    total: "مجموع الديون",
    newCustomer: "زبون جديد",
  },
  cash: {
    daily: "صندوق اليوم",
    shift: "صندوق المناوبة",
    float: "رصيد البداية",
    cashIn: "المحصل نقدا",
    creditOut: "المبيع بالدين",
    expected: "المنتظر في الدرج",
    closeDay: "إغلاق اليوم",
    closeShift: "إغلاق المناوبة",
    closed: "مغلق",
  },
  reports: {
    title: "التقارير",
    today: "اليوم",
    total: "رقم اليوم",
    sales: "المبيعات",
    average: "متوسط البيع",
    best: "الأكثر مبيعا",
    week: "الأيام السبعة الأخيرة",
    print: "طباعة على A4",
    days: "الإثنين|الثلاثاء|الأربعاء|الخميس|الجمعة|السبت|الأحد",
    nothing: "لا مبيعات حتى الآن.",
  },
  settings: {
    title: "الإعدادات",
    shop: "متجرك",
    name: "الاسم",
    phone: "الهاتف",
    address: "العنوان",
    empty: "لم يحدد بعد",
    printing: "الطباعة",
    receipts: "الوصولات والتذاكر على 80 مم",
    documents: "التقارير والوثائق على A4",
    noPrinter: "بدون طابعة: يسجل كل بيع بلا وصل.",
    computers: "الحواسيب",
    staff: "من يحصل المال",
    onlyOwner: "أنت فقط",
    manager: "المسؤول",
    cashier: "أمين الصندوق",
    language: "اللغة",
  },
  overview: {
    salesToday: "مبيعات اليوم",
    lowStock: "منتجات مخزونها منخفض",
    expiring: "تنتهي خلال {name} أشهر",
    credit: "الديون الجارية",
    expensesMonth: "مصاريف الشهر",
  },
  production: {
    title: "إنتاج اليوم",
    made: "أنتج",
    sold: "بيع",
    left: "الباقي",
    addBatch: "دفعة",
    loss: "ما يبقى في المساء يحسب خسارة.",
    resell: "ما يبقى في المساء يباع في الغد.",
    untracked: "ما يبقى في المساء لا يحسب.",
  },
  preorders: {
    title: "الطلبيات المسبقة",
    customer: "الزبون",
    order: "الطلبية",
    due: "موعدها",
    deposit: "عربون",
    noDeposit: "لا يوجد",
    newOrder: "طلبية جديدة",
    today: "اليوم",
    tomorrow: "غدا",
  },
  moves: {
    title: "الإدخال والإخراج",
    all: "كل الأماكن",
    in: "إدخال",
    out: "إخراج",
    product: "المنتج",
    quantity: "الكمية",
    party: "من أو إلى",
    place: "المكان",
    at: "الساعة",
    supplier: "المورد",
    customers: "زبون",
    my_shops: "متجري",
    sites: "ورشة",
    piece: "قطع",
    case: "كراتين",
    kilo: "كغ",
    litre: "لترات",
  },
  rooms: {
    title: "الغرف",
    free: "فارغة",
    occupied: "مشغولة",
    cleaning: "للتنظيف",
    floor: "الطابق",
    count: "{name} مشغولة",
    checkIn: "وصول إلى الغرفة {name}",
    guest: "اسم النزيل",
    nights: "الليالي",
    document: "وثيقة الهوية",
    advance: "عربون",
    confirm: "تأكيد الوصول",
  },
  stays: {
    title: "الحجوزات",
    guest: "النزيل",
    room: "الغرفة",
    arrival: "الوصول",
    nights: "الليالي",
    advance: "عربون",
    balance: "الباقي",
    document: "الوثيقة",
    checked: "تم الاطلاع",
  },
  trips: {
    title: "رحلات اليوم",
    seats: "مقاعد مباعة",
    parcels: "طرود",
    chooseSeat: "اضغط على مقعد فارغ لبيع التذكرة.",
    sellTicket: "بيع تذكرة",
    full: "ممتلئة",
    driver: "السائق",
  },
  parcels: {
    title: "الطرود",
    number: "رقم",
    route: "الرحلة",
    sender: "المرسل",
    receiver: "المستلم",
    paidAtStart: "مدفوع عند الإرسال",
    payOnArrival: "يدفع عند الوصول",
    newParcel: "طرد جديد",
  },
  network: {
    title: "الخطوط",
    route: "الخط",
    price: "التذكرة",
    parcel: "الطرد",
    departures: "رحلات في اليوم",
  },
  expenses: {
    title: "المصاريف",
    what: "المصروف",
    amount: "المبلغ",
    when: "التاريخ",
    newExpense: "مصروف جديد",
    month: "هذا الشهر",
  },
  languages: { fr: "Français", ar: "العربية", en: "English" },
};

export const en: Words = {
  shopPlaceholder: "Your business",
  nav: {
    sale: "Sell",
    counter: "Orders",
    overview: "Dashboard",
    dashboard: "Home",
    menu: "Menu",
    production: "Production",
    preorders: "Orders",
    moves: "Movements",
    rooms: "Rooms",
    stays: "Bookings",
    extras: "Extras",
    trips: "Departures",
    parcels: "Parcels",
    network: "Routes",
    stock: "Stock",
    expenses: "Expenses",
    customers: "Customers",
    cash: "Till",
    reports: "Reports",
    settings: "Settings",
  },
  till: {
    searchName: "Product name",
    searchBarcode: "Barcode",
    searchBoth: "Name or barcode",
    all: "All",
    ticket: "Ticket",
    empty: "Tap a product to start.",
    total: "Total",
    charge: "Take payment",
    credit: "On credit",
    discount: "Discount",
    discountLine: "10 % discount",
    stock: "Stock",
    lowStock: "Low stock",
    out: "Out of stock",
    expires: "Expires",
    expiresSoon: "Expires soon",
    batch: "Batch",
    perKg: "per kg",
    retail: "Box or single units",
    options: "Options",
    optionsFor: "Options: {name}",
    optionList: "No chilli|No onion|Extra cheese",
    add: "Add",
    cancel: "Cancel",
    dineIn: "Eat in",
    takeaway: "Takeaway",
    delivery: "Delivery",
    table: "Table",
    chooseTable: "Choose the table",
    free: "Free",
    zone: "Room",
    sendPrinted: "Send to the kitchen",
    sendSpoken: "Note the order",
    waiting: "Orders waiting",
    noneWaiting: "No orders waiting.",
    todayTotal: "Today's total",
    salesCount: "Sales",
    ordersCount: "Orders",
    cashier: "Cashier",
    manager: "Manager",
    whoOwes: "Who is buying on credit?",
    room: "Room",
    toRoom: "Charge to the room",
    chooseRoom: "Which room?",
    kitchenTicket: "Kitchen",
    overLimit: "Over the limit",
    owes: "Owes",
  },
  notes: {
    saved: "Sale recorded.",
    printed: "Sale recorded. Receipt printed.",
    credit: "Added to {name}'s account.",
    kitchenPrinted: "Ticket printed in the kitchen.",
    kitchenSpoken: "Order noted.",
    roomCharged: "Added to room {name}.",
    checkedIn: "Room {name} is taken.",
    seatSold: "Seat {name} sold.",
    ticketSold: "Ticket sold.",
    parcelAdded: "Parcel recorded.",
    moveAdded: "Movement recorded.",
    batchAdded: "Batch added.",
    closedDay: "Day closed. The report is ready.",
    closedShift: "Shift closed. The report is ready.",
    orderAdded: "Order noted.",
    expenseAdded: "Expense noted.",
    received: "Delivery recorded.",
  },
  stock: {
    title: "Stock",
    product: "Product",
    quantity: "Quantity",
    price: "Price",
    expiry: "Expiry",
    batch: "Batch",
    supplier: "Supplier",
    newProduct: "New product",
    receive: "Delivery in",
    services: "Services",
    available: "Available",
  },
  customers: {
    title: "Customers",
    name: "Customer",
    owes: "Owes",
    limit: "Limit",
    nothing: "Nothing",
    total: "Total owed",
    newCustomer: "New customer",
  },
  cash: {
    daily: "Today's till",
    shift: "This shift's till",
    float: "Opening cash",
    cashIn: "Taken in cash",
    creditOut: "Sold on credit",
    expected: "Expected in the drawer",
    closeDay: "Close the day",
    closeShift: "Close the shift",
    closed: "Closed",
  },
  reports: {
    title: "Reports",
    today: "Today",
    total: "Today's takings",
    sales: "Sales",
    average: "Average sale",
    best: "Best sellers",
    week: "The last seven days",
    print: "Print on A4",
    days: "Mon|Tue|Wed|Thu|Fri|Sat|Sun",
    nothing: "No sales yet.",
  },
  settings: {
    title: "Settings",
    shop: "Your business",
    name: "Name",
    phone: "Phone",
    address: "Address",
    empty: "Not filled in yet",
    printing: "Printing",
    receipts: "Receipts and tickets on 80 mm",
    documents: "Reports and documents on A4",
    noPrinter: "No printer: every sale is recorded, without a receipt.",
    computers: "Computers",
    staff: "Who takes the money",
    onlyOwner: "Only you",
    manager: "Manager",
    cashier: "Cashier",
    language: "Language",
  },
  overview: {
    salesToday: "Today's sales",
    lowStock: "Products low in stock",
    expiring: "Expire within {name} months",
    credit: "Money owed",
    expensesMonth: "This month's expenses",
  },
  production: {
    title: "Today's production",
    made: "Made",
    sold: "Sold",
    left: "Left",
    addBatch: "Batch",
    loss: "What is left in the evening counts as a loss.",
    resell: "What is left in the evening is sold the next day.",
    untracked: "What is left in the evening is not counted.",
  },
  preorders: {
    title: "Orders in advance",
    customer: "Customer",
    order: "Order",
    due: "For",
    deposit: "Deposit",
    noDeposit: "None",
    newOrder: "New order",
    today: "Today",
    tomorrow: "Tomorrow",
  },
  moves: {
    title: "Goods in and out",
    all: "All places",
    in: "In",
    out: "Out",
    product: "Product",
    quantity: "Quantity",
    party: "From or to",
    place: "Place",
    at: "Time",
    supplier: "Supplier",
    customers: "Customer",
    my_shops: "My shop",
    sites: "Site",
    piece: "pieces",
    case: "cases",
    kilo: "kg",
    litre: "litres",
  },
  rooms: {
    title: "Rooms",
    free: "Free",
    occupied: "Taken",
    cleaning: "To clean",
    floor: "Floor",
    count: "{name} taken",
    checkIn: "Check-in to room {name}",
    guest: "Guest's name",
    nights: "Nights",
    document: "ID document",
    advance: "Advance",
    confirm: "Confirm check-in",
  },
  stays: {
    title: "Bookings",
    guest: "Guest",
    room: "Room",
    arrival: "Arrival",
    nights: "Nights",
    advance: "Advance",
    balance: "Left to pay",
    document: "ID",
    checked: "Seen",
  },
  trips: {
    title: "Today's departures",
    seats: "seats sold",
    parcels: "parcels",
    chooseSeat: "Tap a free seat to sell the ticket.",
    sellTicket: "Sell a ticket",
    full: "Full",
    driver: "Driver",
  },
  parcels: {
    title: "Parcels",
    number: "No.",
    route: "Route",
    sender: "Sender",
    receiver: "Receiver",
    paidAtStart: "Paid at departure",
    payOnArrival: "To pay on arrival",
    newParcel: "New parcel",
  },
  network: {
    title: "Routes",
    route: "Route",
    price: "Ticket",
    parcel: "Parcel",
    departures: "Departures a day",
  },
  expenses: {
    title: "Expenses",
    what: "Expense",
    amount: "Amount",
    when: "Date",
    newExpense: "New expense",
    month: "This month",
  },
  languages: { fr: "Français", ar: "العربية", en: "English" },
};

const all: Record<AppLanguage, Words> = { fr, ar, en };

export function wordsFor(language: AppLanguage): Words {
  return all[language] ?? fr;
}

/** A sentence with its "{name}" filled in. */
export function fill(template: string, value: string | number): string {
  return template.replace("{name}", String(value));
}

/** "Stock : 12" in French, "Stock: 12" elsewhere: French sets a space before the colon. */
export function labelled(language: AppLanguage, label: string, value: string | number): string {
  return language === "fr" ? `${label} : ${value}` : `${label}: ${value}`;
}

/** A list written as one string, "a|b|c", which keeps every language the same shape. */
export function list(value: string): string[] {
  return value.split("|");
}
