import type { AdminLanguage } from "./copy";

/*
 * The words of the statistics page and the representatives' pages, in the
 * three admin languages. Kept beside copy.ts rather than inside it, with the
 * same rule: French is the reference and the other two must match its shape.
 */

const fr = {
  stats: {
    title: "Statistiques",
    intro: "Tout OUAQT en chiffres. Chaque chiffre est comparé à la période précédente de même durée : la flèche dit s'il monte ou s'il baisse.",
    periods: { 7: "7 jours", 30: "30 jours", 90: "90 jours", 365: "12 mois" } as Record<number, string>,
    versus: "Comparé aux {days} jours précédents.",
    before: "{value} la période d'avant",
    trendNew: "nouveau",
    trendFlat: "stable",
    metrics: {
      visitors: "Visiteurs du site",
      builder: "Ont ouvert le Builder",
      serials: "Numéros de série donnés",
      downloads: "Téléchargements",
      activations: "Ordinateurs activés",
      shops: "Commerces créés",
      trials: "Essais démarrés",
      paying: "Nouveaux clients payants",
      revenue: "Encaissé",
    },
    hints: {
      visitors: "Un onglet compte une fois, quel que soit le nombre de pages lues.",
      builder: "Ont commencé à répondre aux questions.",
      serials: "Ont fini les questions et reçu leur numéro.",
      downloads: "Clics sur un bouton de téléchargement.",
      activations: "Logiciels ouverts pour la première fois sur un ordinateur.",
      shops: "Commerces créés à partir d'un numéro de série.",
      trials: "Essais gratuits commencés sur un ordinateur.",
      paying: "Commerces dont le premier paiement a été confirmé.",
      revenue: "Paiements confirmés sur la période.",
    },
    chartTitle: "Évolution",
    chartTotal: "total sur la période",
    chartWeek: "semaine du {date}",
    chartEmpty: "Rien sur cette période pour l'instant.",
    funnelTitle: "Du visiteur au client payant",
    funnelIntro: "Sur la période : combien passent d'une étape à la suivante, et ce qu'il reste des visiteurs à chaque étape.",
    ofPrevious: "{rate} de l'étape d'avant",
    ofFirst: "{rate} des visiteurs",
    productionTitle: "En production maintenant",
    productionIntro: "L'état d'aujourd'hui, quelle que soit la période choisie.",
    production: {
      shops: "Commerces",
      computers: "Ordinateurs activés",
      onlineNow: "Ouverts en ce moment",
      onlineToday: "Vus aujourd'hui",
      onlineWeek: "Vus ces 7 jours",
      systems: "Windows {windows} · Mac {mac}",
      licences: "Licences",
      none: "Sans licence",
    },
    revenueTitle: "Revenus",
    revenue: {
      allTime: "Depuis le lancement",
      payingShops: "{count} commerces ont déjà payé",
      average: "Paiement moyen sur la période",
      byPlan: "Par formule, sur la période",
      byApp: "Par application de paiement, sur la période",
      none: "Aucun paiement sur la période.",
    },
    breakdownTitle: "Répartition sur la période",
    breakdown: {
      tradesBuilt: "Métiers créés",
      tradesDownloaded: "Métiers téléchargés",
      languages: "Langue des visiteurs",
      devices: "Appareil des visiteurs",
      systems: "Système téléchargé",
      pages: "Pages les plus vues",
      phone: "Téléphone",
      desktop: "Ordinateur",
      home: "Accueil",
      unknown: "Inconnu",
      empty: "Rien encore.",
    },
    languages: { fr: "Français", ar: "Arabe", en: "Anglais" } as Record<string, string>,
    systems: { windows: "Windows", mac: "Mac" } as Record<string, string>,
    demandTitle: "Ce que les visiteurs demandent",
    demand: {
      leads: "Métiers non couverts demandés",
      requests: "Demandes de fonctions",
      topLeads: "Les métiers les plus demandés",
    },
    repsTitle: "Commerciaux",
    repsIntro: "Ce que chaque commercial a apporté sur la période. Le bonus se calcule sur tout ce que ses commerces ont payé depuis le début.",
    repsEmpty: "Aucun commercial pour l'instant.",
    repsManage: "Gérer les commerciaux",
    columns: {
      name: "Commercial",
      visits: "Visiteurs",
      serials: "Numéros",
      shops: "Commerces",
      paying: "Payants",
      revenue: "Encaissé",
      due: "Bonus à verser",
    },
  },

  reps: {
    title: "Commerciaux",
    intro: "Chaque commercial a un code et un QR code à lui. Les commerces arrivés par son QR code lui sont attribués, et son bonus se calcule sur ce qu'ils paient.",
    howTitle: "Comment c'est compté",
    how: [
      "Le QR code ouvre www.ouaqt.com avec le code du commercial. Le site le garde 30 jours dans ce navigateur, et le premier commercial reste celui qui compte.",
      "Quand ce visiteur reçoit son numéro de série, son commerce est attribué au commercial, sur quel ordinateur qu'il installe ensuite.",
      "Le bonus : une part de ce que ses commerces paient, et un montant fixe par commerce qui paie. Vous le réglez pour chaque commercial.",
      "Un client venu sans scanner le QR code s'attribue à la main, depuis sa fiche client.",
    ],
    empty: "Aucun commercial pour l'instant. Ajoutez le premier ci-dessous.",
    addTitle: "Ajouter un commercial",
    addIntro: "Son code et son QR code sont créés tout de suite.",
    name: "Nom",
    phone: "Téléphone (facultatif)",
    percent: "Commission (%)",
    percentHint: "Part de ce que paient ses commerces.",
    perShop: "Bonus par commerce payant (MRU)",
    perShopHint: "Versé une fois pour chaque commerce qui paie.",
    note: "Note (facultatif)",
    add: "Ajouter le commercial",
    added: "{name} est ajouté, avec le code {code}.",
    inactive: "Désactivé",
    code: "Code",
    link: "Son lien",
    copyLink: "Copier le lien",
    copied: "Lien copié",
    downloadQr: "Télécharger le QR code",
    printCard: "Carte à imprimer",
    open: "Voir",
    rulePercent: "{percent} % de ce que paient ses commerces",
    rulePerShop: "{perShop} par commerce payant",
    ruleNone: "Aucun bonus réglé",
    since: "Depuis le {date}",
    figures: {
      visits: "Visiteurs",
      serials: "Numéros donnés",
      shops: "Commerces",
      paying: "Commerces payants",
      revenue: "Encaissé",
      earned: "Bonus gagné",
      paid: "Déjà versé",
      due: "Reste à verser",
    },
    periodLabel: "Ces 30 derniers jours",
    allTimeLabel: "Depuis le début",
    shopsTitle: "Ses commerces",
    shopsEmpty: "Aucun commerce encore.",
    shopColumns: { name: "Commerce", trade: "Métier", since: "Créé le", status: "Licence", paid: "Payé" },
    payoutsTitle: "Versements",
    payoutsEmpty: "Aucun versement encore.",
    payoutAmount: "Montant versé (MRU)",
    payoutNote: "Note (facultatif)",
    payoutAdd: "Enregistrer le versement",
    payoutSaved: "Versement enregistré.",
    editTitle: "Bonus et coordonnées",
    save: "Enregistrer",
    saved: "Enregistré.",
    deactivate: "Désactiver",
    reactivate: "Réactiver",
    activeHint: "Désactivé, il n'est plus attribué de nouveaux commerces ; ce qu'il a déjà gagné reste ici.",
    back: "Tous les commerciaux",
    cardHeading: "Votre logiciel de gestion, prêt en quelques minutes",
    cardHeadingAr: "برنامج تسيير متجرك، جاهز في دقائق",
    cardScan: "Scannez pour commencer · امسح الرمز للبدء",
    cardBy: "Présenté par {name}",
    print: "Imprimer",
    assignTitle: "Commercial",
    assignNone: "Aucun",
    assignSave: "Attribuer",
    assignSaved: "Commercial enregistré.",
    assignHint: "Le commercial qui a apporté ce commerce. Son bonus compte les paiements de ce commerce.",
    errors: {
      invalid: "Vérifiez les champs.",
      not_saved: "Non enregistré, réessayez.",
      not_found: "Ce commercial n'existe plus.",
      failed: "Pas de réponse, vérifiez la connexion.",
      no_database: "Base de données injoignable.",
    } as Record<string, string>,
  },
  control: {
    title: "Contrôle des logiciels",
    intro: "Ce que chaque commerce peut faire avec son logiciel, et tout ce que vous pouvez y changer : l'offrir à vie, l'arrêter, prolonger ou arrêter un essai, suspendre, bannir.",
    timing: "Une décision arrive sur l'ordinateur du commerce à sa prochaine vérification : à l'ouverture du logiciel, et toutes les 3 heures tant qu'il a internet.",
    search: "Chercher un commerce : nom ou téléphone",
    searchButton: "Chercher",
    clear: "Effacer",
    groups: {
      all: "Tous",
      trial: "En essai",
      trial_over: "Essai terminé",
      paid: "Payants",
      lifetime: "Offerts à vie",
      renewal: "À renouveler",
      expired: "Expirés",
      suspended: "Suspendus",
      banned: "Bannis",
      none: "Sans licence",
    } as Record<string, string>,
    empty: "Aucun commerce ici.",
    badge: { banned: "Banni", lifetime: "Offert à vie" },
    line: {
      trialLeft: "Essai · {days} jours restants",
      trialNotStarted: "Essai · pas encore ouvert sur un ordinateur",
      trialOver: "Essai terminé le {date}",
      until: "Licence jusqu'au {date}",
      renewal: "Échue le {date} · en délai de grâce",
      expired: "Expirée le {date}",
      cancelled: "Annulée le {date}",
      lifetimeGift: "À vie · offerte",
      lifetimePaid: "À vie · payée",
      suspended: "Suspendue",
      banned: "Banni le {date}",
      none: "Aucune licence",
    },
    computersOne: "1 ordinateur",
    computersMany: "{count} ordinateurs",
    computersNone: "Aucun ordinateur activé",
    lastSeen: "vu {ago}",
    manage: "Gérer",
    close: "Fermer",
    openClient: "Fiche client",
    sections: { access: "Donner l'accès", stop: "Arrêter", sanction: "Sanctions" },
    actions: {
      gift: { label: "Offrir à vie, gratuit", hint: "Une licence permanente offerte. Elle ne compte pas dans l'encaissé et s'annule à tout moment.", confirm: "Offrir à vie" },
      grant: { label: "Donner une formule", hint: "Une formule réglée hors du site, en espèces ou par virement. Le temps s'ajoute à la fin actuelle.", confirm: "Donner la formule" },
      extend: { label: "Prolonger", hint: "Des jours ajoutés à la fin, ou à partir d'aujourd'hui si elle est passée. Un essai fini redevient un essai.", confirm: "Prolonger" },
      stop_trial: { label: "Arrêter l'essai", hint: "L'essai se termine maintenant : le logiciel passe en lecture seule. Rien n'est effacé.", confirm: "Arrêter l'essai" },
      cancel: { label: "Annuler la licence", hint: "Elle prend fin maintenant, sans délai de grâce, même à vie : le logiciel passe en lecture seule. Le commerce peut payer une licence pour le rouvrir.", confirm: "Annuler la licence" },
      suspend: { label: "Suspendre", hint: "Lecture seule jusqu'à ce que vous le réactiviez. Rien n'est effacé, les dates ne bougent pas.", confirm: "Suspendre" },
      reactivate: { label: "Réactiver", hint: "La suspension est levée : la licence redevient ce qu'elle était.", confirm: "Réactiver" },
      ban: { label: "Bannir", hint: "Suspendu, aucun nouvel ordinateur ne peut l'activer, et ses ordinateurs ne peuvent ouvrir aucun autre commerce.", confirm: "Bannir" },
      unban: { label: "Lever le bannissement", hint: "Le commerce retrouve sa licence telle qu'elle était avant.", confirm: "Lever le bannissement" },
    },
    reason: "Raison, gardée dans l'historique",
    days: "Jours",
    plan: "Formule",
    planNames: { annual: "Annuelle", semiannual: "Semestrielle", perpetual: "Définitive, payée" } as Record<string, string>,
    cancelAction: "Annuler",
    done: "C'est fait. Le logiciel l'appliquera à sa prochaine vérification.",
    errors: {
      banned: "Ce commerce est banni : levez d'abord le bannissement.",
      already: "C'est déjà le cas.",
      perpetual: "Une licence à vie n'a pas de fin à déplacer.",
      no_licence: "Ce commerce n'a pas encore de licence.",
      not_found: "Commerce introuvable.",
      not_saved: "Non enregistré, réessayez.",
      invalid: "Vérifiez les champs : la raison doit faire au moins 4 caractères.",
      failed: "Pas de réponse, vérifiez la connexion.",
    } as Record<string, string>,
  },
};

export type GrowthCopy = typeof fr;

const en: GrowthCopy = {
  stats: {
    title: "Statistics",
    intro: "All of OUAQT in numbers. Every figure is compared with the previous period of the same length: the arrow says whether it is going up or down.",
    periods: { 7: "7 days", 30: "30 days", 90: "90 days", 365: "12 months" },
    versus: "Compared with the previous {days} days.",
    before: "{value} the period before",
    trendNew: "new",
    trendFlat: "steady",
    metrics: {
      visitors: "Site visitors",
      builder: "Opened the Builder",
      serials: "Serial numbers given",
      downloads: "Downloads",
      activations: "Computers activated",
      shops: "Shops created",
      trials: "Trials started",
      paying: "New paying customers",
      revenue: "Received",
    },
    hints: {
      visitors: "A browser tab counts once, however many pages it reads.",
      builder: "Started answering the questions.",
      serials: "Finished the questions and got their number.",
      downloads: "Presses on a download button.",
      activations: "Software opened for the first time on a computer.",
      shops: "Shops created from a serial number.",
      trials: "Free trials started on a computer.",
      paying: "Shops whose first payment was confirmed.",
      revenue: "Confirmed payments in the period.",
    },
    chartTitle: "Over time",
    chartTotal: "total for the period",
    chartWeek: "week of {date}",
    chartEmpty: "Nothing in this period yet.",
    funnelTitle: "From visitor to paying customer",
    funnelIntro: "In the period: how many move from one step to the next, and what is left of the visitors at each step.",
    ofPrevious: "{rate} of the step before",
    ofFirst: "{rate} of visitors",
    productionTitle: "In production now",
    productionIntro: "Where things stand today, whatever the period chosen.",
    production: {
      shops: "Shops",
      computers: "Computers activated",
      onlineNow: "Open right now",
      onlineToday: "Seen today",
      onlineWeek: "Seen in 7 days",
      systems: "Windows {windows} · Mac {mac}",
      licences: "Licences",
      none: "No licence",
    },
    revenueTitle: "Revenue",
    revenue: {
      allTime: "Since launch",
      payingShops: "{count} shops have paid so far",
      average: "Average payment in the period",
      byPlan: "By plan, in the period",
      byApp: "By payment app, in the period",
      none: "No payment in the period.",
    },
    breakdownTitle: "Breakdown for the period",
    breakdown: {
      tradesBuilt: "Trades built",
      tradesDownloaded: "Trades downloaded",
      languages: "Visitors' language",
      devices: "Visitors' device",
      systems: "System downloaded",
      pages: "Most viewed pages",
      phone: "Phone",
      desktop: "Computer",
      home: "Home",
      unknown: "Unknown",
      empty: "Nothing yet.",
    },
    languages: { fr: "French", ar: "Arabic", en: "English" },
    systems: { windows: "Windows", mac: "Mac" },
    demandTitle: "What visitors ask for",
    demand: {
      leads: "Uncovered trades asked for",
      requests: "Feature requests",
      topLeads: "Most asked-for trades",
    },
    repsTitle: "Sales representatives",
    repsIntro: "What each representative brought in the period. The bonus is worked out on everything their shops have paid since the start.",
    repsEmpty: "No representative yet.",
    repsManage: "Manage representatives",
    columns: {
      name: "Representative",
      visits: "Visitors",
      serials: "Serials",
      shops: "Shops",
      paying: "Paying",
      revenue: "Received",
      due: "Bonus owed",
    },
  },

  reps: {
    title: "Sales representatives",
    intro: "Each representative has a code and a QR code of their own. Shops that arrive through their QR code are credited to them, and their bonus is worked out on what those shops pay.",
    howTitle: "How it is counted",
    how: [
      "The QR code opens www.ouaqt.com with the representative's code. The site keeps it in that browser for 30 days, and the first representative is the one that counts.",
      "When that visitor gets their serial number, their shop is credited to the representative, whichever computer it is then installed on.",
      "The bonus: a share of what their shops pay, and a fixed amount for each shop that pays. You set it for each representative.",
      "A customer who came without scanning the QR code is credited by hand, from their customer page.",
    ],
    empty: "No representative yet. Add the first one below.",
    addTitle: "Add a representative",
    addIntro: "Their code and QR code are made straight away.",
    name: "Name",
    phone: "Phone (optional)",
    percent: "Commission (%)",
    percentHint: "Share of what their shops pay.",
    perShop: "Bonus per paying shop (MRU)",
    perShopHint: "Paid once for each shop that pays.",
    note: "Note (optional)",
    add: "Add the representative",
    added: "{name} is added, with the code {code}.",
    inactive: "Deactivated",
    code: "Code",
    link: "Their link",
    copyLink: "Copy the link",
    copied: "Link copied",
    downloadQr: "Download the QR code",
    printCard: "Printable card",
    open: "Open",
    rulePercent: "{percent}% of what their shops pay",
    rulePerShop: "{perShop} per paying shop",
    ruleNone: "No bonus set",
    since: "Since {date}",
    figures: {
      visits: "Visitors",
      serials: "Serials given",
      shops: "Shops",
      paying: "Paying shops",
      revenue: "Received",
      earned: "Bonus earned",
      paid: "Already paid",
      due: "Still to pay",
    },
    periodLabel: "The last 30 days",
    allTimeLabel: "Since the start",
    shopsTitle: "Their shops",
    shopsEmpty: "No shop yet.",
    shopColumns: { name: "Shop", trade: "Trade", since: "Created", status: "Licence", paid: "Paid" },
    payoutsTitle: "Payouts",
    payoutsEmpty: "No payout yet.",
    payoutAmount: "Amount paid (MRU)",
    payoutNote: "Note (optional)",
    payoutAdd: "Record the payout",
    payoutSaved: "Payout recorded.",
    editTitle: "Bonus and details",
    save: "Save",
    saved: "Saved.",
    deactivate: "Deactivate",
    reactivate: "Reactivate",
    activeHint: "Deactivated, they are credited no new shops; what they have earned stays here.",
    back: "All representatives",
    cardHeading: "Your management software, ready in minutes",
    cardHeadingAr: "برنامج تسيير متجرك، جاهز في دقائق",
    cardScan: "Scan to start · امسح الرمز للبدء",
    cardBy: "Presented by {name}",
    print: "Print",
    assignTitle: "Sales representative",
    assignNone: "None",
    assignSave: "Credit",
    assignSaved: "Representative saved.",
    assignHint: "The representative who brought this shop. Their bonus counts this shop's payments.",
    errors: {
      invalid: "Check the fields.",
      not_saved: "Not saved, try again.",
      not_found: "This representative no longer exists.",
      failed: "No answer, check the connection.",
      no_database: "Database unreachable.",
    },
  },
  control: {
    title: "Software control",
    intro: "What each shop can do with its software, and everything you can change: give it for life, end it, extend or stop a trial, suspend, ban.",
    timing: "A decision reaches the shop's computer at its next check: when the software opens, and every 3 hours while it has internet.",
    search: "Find a shop: name or phone",
    searchButton: "Search",
    clear: "Clear",
    groups: {
      all: "All",
      trial: "On trial",
      trial_over: "Trial ended",
      paid: "Paying",
      lifetime: "Given for life",
      renewal: "To renew",
      expired: "Expired",
      suspended: "Suspended",
      banned: "Banned",
      none: "No licence",
    },
    empty: "No shop here.",
    badge: { banned: "Banned", lifetime: "Given for life" },
    line: {
      trialLeft: "Trial · {days} days left",
      trialNotStarted: "Trial · not opened on a computer yet",
      trialOver: "Trial ended on {date}",
      until: "Licence until {date}",
      renewal: "Due since {date} · in its grace period",
      expired: "Expired on {date}",
      cancelled: "Cancelled on {date}",
      lifetimeGift: "For life · given",
      lifetimePaid: "For life · paid",
      suspended: "Suspended",
      banned: "Banned on {date}",
      none: "No licence",
    },
    computersOne: "1 computer",
    computersMany: "{count} computers",
    computersNone: "No computer activated",
    lastSeen: "seen {ago}",
    manage: "Manage",
    close: "Close",
    openClient: "Customer page",
    sections: { access: "Give access", stop: "End", sanction: "Sanctions" },
    actions: {
      gift: { label: "Give for life, free", hint: "A permanent licence, given. It never counts as money received and can be cancelled at any time.", confirm: "Give for life" },
      grant: { label: "Give a plan", hint: "A plan paid outside the site, in cash or by transfer. The time is added to the current end.", confirm: "Give the plan" },
      extend: { label: "Extend", hint: "Days added to the end, or from today if it has passed. An ended trial becomes a trial again.", confirm: "Extend" },
      stop_trial: { label: "Stop the trial", hint: "The trial ends now: the software turns read-only. Nothing is deleted.", confirm: "Stop the trial" },
      cancel: { label: "Cancel the licence", hint: "It ends now, with no grace, even a lifetime one: the software turns read-only. The shop can pay for a licence to open it again.", confirm: "Cancel the licence" },
      suspend: { label: "Suspend", hint: "Read-only until you reactivate it. Nothing is deleted, the dates do not move.", confirm: "Suspend" },
      reactivate: { label: "Reactivate", hint: "The suspension is lifted: the licence is what it was.", confirm: "Reactivate" },
      ban: { label: "Ban", hint: "Suspended, no new computer may activate it, and its computers may not open any other shop.", confirm: "Ban" },
      unban: { label: "Lift the ban", hint: "The shop gets its licence back as it was before.", confirm: "Lift the ban" },
    },
    reason: "Reason, kept in the history",
    days: "Days",
    plan: "Plan",
    planNames: { annual: "Annual", semiannual: "Six months", perpetual: "Permanent, paid" },
    cancelAction: "Cancel",
    done: "Done. The software will apply it at its next check.",
    errors: {
      banned: "This shop is banned: lift the ban first.",
      already: "It already is.",
      perpetual: "A lifetime licence has no end to move.",
      no_licence: "This shop has no licence yet.",
      not_found: "Shop not found.",
      not_saved: "Not saved, try again.",
      invalid: "Check the fields: the reason needs at least 4 characters.",
      failed: "No answer, check the connection.",
    },
  },
};

const ar: GrowthCopy = {
  stats: {
    title: "الإحصائيات",
    intro: "كل «وقت» بالأرقام. كل رقم يقارَن بالفترة السابقة من المدة نفسها: يبين السهم إن كان يرتفع أو ينخفض.",
    periods: { 7: "7 أيام", 30: "30 يوما", 90: "90 يوما", 365: "12 شهرا" },
    versus: "مقارنة بالأيام الـ{days} السابقة.",
    before: "{value} في الفترة السابقة",
    trendNew: "جديد",
    trendFlat: "مستقر",
    metrics: {
      visitors: "زوار الموقع",
      builder: "فتحوا المنشئ",
      serials: "أرقام تسلسلية مسلمة",
      downloads: "التنزيلات",
      activations: "حواسيب مفعلة",
      shops: "محلات أنشئت",
      trials: "تجارب بدأت",
      paying: "زبائن دافعون جدد",
      revenue: "المحصّل",
    },
    hints: {
      visitors: "تُعدّ نافذة المتصفح مرة واحدة مهما قرأت من صفحات.",
      builder: "بدأوا الإجابة عن الأسئلة.",
      serials: "أنهوا الأسئلة واستلموا رقمهم.",
      downloads: "نقرات على زر التنزيل.",
      activations: "برامج فُتحت أول مرة على حاسوب.",
      shops: "محلات أنشئت من رقم تسلسلي.",
      trials: "تجارب مجانية بدأت على حاسوب.",
      paying: "محلات تأكد أول دفع لها.",
      revenue: "مدفوعات مؤكدة في الفترة.",
    },
    chartTitle: "التطور",
    chartTotal: "مجموع الفترة",
    chartWeek: "أسبوع {date}",
    chartEmpty: "لا شيء في هذه الفترة بعد.",
    funnelTitle: "من الزائر إلى الزبون الدافع",
    funnelIntro: "في الفترة: كم ينتقل من خطوة إلى التالية، وكم يبقى من الزوار عند كل خطوة.",
    ofPrevious: "{rate} من الخطوة السابقة",
    ofFirst: "{rate} من الزوار",
    productionTitle: "قيد الاستعمال الآن",
    productionIntro: "حال اليوم، مهما كانت الفترة المختارة.",
    production: {
      shops: "المحلات",
      computers: "حواسيب مفعلة",
      onlineNow: "مفتوحة الآن",
      onlineToday: "شوهدت اليوم",
      onlineWeek: "شوهدت في 7 أيام",
      systems: "ويندوز {windows} · ماك {mac}",
      licences: "الرخص",
      none: "دون رخصة",
    },
    revenueTitle: "المداخيل",
    revenue: {
      allTime: "منذ الانطلاق",
      payingShops: "{count} محلات دفعت حتى الآن",
      average: "متوسط الدفع في الفترة",
      byPlan: "حسب الصيغة، في الفترة",
      byApp: "حسب تطبيق الدفع، في الفترة",
      none: "لا دفع في هذه الفترة.",
    },
    breakdownTitle: "التوزيع في الفترة",
    breakdown: {
      tradesBuilt: "الأنشطة المنشأة",
      tradesDownloaded: "الأنشطة المنزّلة",
      languages: "لغة الزوار",
      devices: "جهاز الزوار",
      systems: "النظام المنزّل",
      pages: "الصفحات الأكثر زيارة",
      phone: "هاتف",
      desktop: "حاسوب",
      home: "الرئيسية",
      unknown: "غير معروف",
      empty: "لا شيء بعد.",
    },
    languages: { fr: "الفرنسية", ar: "العربية", en: "الإنجليزية" },
    systems: { windows: "ويندوز", mac: "ماك" },
    demandTitle: "ما يطلبه الزوار",
    demand: {
      leads: "أنشطة غير مغطاة مطلوبة",
      requests: "طلبات وظائف",
      topLeads: "الأنشطة الأكثر طلبا",
    },
    repsTitle: "المندوبون التجاريون",
    repsIntro: "ما جلبه كل مندوب في الفترة. تُحسب المكافأة على كل ما دفعته محلاته منذ البداية.",
    repsEmpty: "لا مندوب بعد.",
    repsManage: "إدارة المندوبين",
    columns: {
      name: "المندوب",
      visits: "الزوار",
      serials: "الأرقام",
      shops: "المحلات",
      paying: "الدافعون",
      revenue: "المحصّل",
      due: "المكافأة المستحقة",
    },
  },

  reps: {
    title: "المندوبون التجاريون",
    intro: "لكل مندوب رمز ورمز QR خاص به. تُنسب إليه المحلات التي تأتي عبر رمزه، وتُحسب مكافأته على ما تدفعه.",
    howTitle: "كيف يُحتسب",
    how: [
      "يفتح رمز QR موقع www.ouaqt.com مع رمز المندوب. يحفظه الموقع في ذلك المتصفح 30 يوما، ويبقى المندوب الأول هو المعتبر.",
      "حين يستلم هذا الزائر رقمه التسلسلي، يُنسب محله إلى المندوب، على أي حاسوب ثبّته بعد ذلك.",
      "المكافأة: نسبة مما تدفعه محلاته، ومبلغ ثابت عن كل محل يدفع. تحددها لكل مندوب.",
      "الزبون الذي جاء دون مسح الرمز يُنسب يدويا من صفحته.",
    ],
    empty: "لا مندوب بعد. أضف الأول أدناه.",
    addTitle: "إضافة مندوب",
    addIntro: "يُنشأ رمزه ورمز QR الخاص به فورا.",
    name: "الاسم",
    phone: "الهاتف (اختياري)",
    percent: "العمولة (%)",
    percentHint: "نسبة مما تدفعه محلاته.",
    perShop: "مكافأة عن كل محل دافع (أوقية)",
    perShopHint: "تُدفع مرة واحدة عن كل محل يدفع.",
    note: "ملاحظة (اختياري)",
    add: "إضافة المندوب",
    added: "أضيف {name} بالرمز {code}.",
    inactive: "موقوف",
    code: "الرمز",
    link: "رابطه",
    copyLink: "نسخ الرابط",
    copied: "نُسخ الرابط",
    downloadQr: "تنزيل رمز QR",
    printCard: "بطاقة للطباعة",
    open: "عرض",
    rulePercent: "{percent}٪ مما تدفعه محلاته",
    rulePerShop: "{perShop} عن كل محل دافع",
    ruleNone: "لم تحدد مكافأة",
    since: "منذ {date}",
    figures: {
      visits: "الزوار",
      serials: "أرقام مسلمة",
      shops: "المحلات",
      paying: "محلات دافعة",
      revenue: "المحصّل",
      earned: "المكافأة المكتسبة",
      paid: "ما دُفع",
      due: "المتبقي للدفع",
    },
    periodLabel: "آخر 30 يوما",
    allTimeLabel: "منذ البداية",
    shopsTitle: "محلاته",
    shopsEmpty: "لا محل بعد.",
    shopColumns: { name: "المحل", trade: "النشاط", since: "أنشئ في", status: "الرخصة", paid: "المدفوع" },
    payoutsTitle: "الدفعات",
    payoutsEmpty: "لا دفعة بعد.",
    payoutAmount: "المبلغ المدفوع (أوقية)",
    payoutNote: "ملاحظة (اختياري)",
    payoutAdd: "تسجيل الدفعة",
    payoutSaved: "سُجلت الدفعة.",
    editTitle: "المكافأة والمعلومات",
    save: "حفظ",
    saved: "حُفظ.",
    deactivate: "إيقاف",
    reactivate: "إعادة التفعيل",
    activeHint: "إذا أوقف لا تُنسب إليه محلات جديدة؛ ويبقى ما اكتسبه ظاهرا هنا.",
    back: "كل المندوبين",
    cardHeading: "Votre logiciel de gestion, prêt en quelques minutes",
    cardHeadingAr: "برنامج تسيير متجرك، جاهز في دقائق",
    cardScan: "Scannez pour commencer · امسح الرمز للبدء",
    cardBy: "يقدّمه {name}",
    print: "طباعة",
    assignTitle: "المندوب التجاري",
    assignNone: "لا أحد",
    assignSave: "نسبة",
    assignSaved: "حُفظ المندوب.",
    assignHint: "المندوب الذي جلب هذا المحل. تحتسب مكافأته مدفوعات هذا المحل.",
    errors: {
      invalid: "تحقق من الحقول.",
      not_saved: "لم يُحفظ، أعد المحاولة.",
      not_found: "هذا المندوب لم يعد موجودا.",
      failed: "لا رد، تحقق من الاتصال.",
      no_database: "قاعدة البيانات غير متاحة.",
    },
  },
  control: {
    title: "التحكم في البرامج",
    intro: "ما يستطيع كل محل فعله ببرنامجه، وكل ما يمكنك تغييره: منحه مدى الحياة، إنهاؤه، تمديد التجربة أو إيقافها، التعليق، الحظر.",
    timing: "يصل القرار إلى حاسوب المحل عند فحصه التالي: عند فتح البرنامج، وكل 3 ساعات ما دام متصلا بالإنترنت.",
    search: "ابحث عن محل: الاسم أو الهاتف",
    searchButton: "بحث",
    clear: "مسح",
    groups: {
      all: "الكل",
      trial: "في التجربة",
      trial_over: "انتهت التجربة",
      paid: "دافعون",
      lifetime: "ممنوحة مدى الحياة",
      renewal: "للتجديد",
      expired: "منتهية",
      suspended: "معلّقة",
      banned: "محظورة",
      none: "دون رخصة",
    },
    empty: "لا محل هنا.",
    badge: { banned: "محظور", lifetime: "ممنوح مدى الحياة" },
    line: {
      trialLeft: "تجربة · بقي {days} يوما",
      trialNotStarted: "تجربة · لم تُفتح على حاسوب بعد",
      trialOver: "انتهت التجربة في {date}",
      until: "رخصة حتى {date}",
      renewal: "مستحقة منذ {date} · في مهلة السماح",
      expired: "انتهت في {date}",
      cancelled: "أُلغيت في {date}",
      lifetimeGift: "مدى الحياة · ممنوحة",
      lifetimePaid: "مدى الحياة · مدفوعة",
      suspended: "معلّقة",
      banned: "محظور منذ {date}",
      none: "لا رخصة",
    },
    computersOne: "حاسوب واحد",
    computersMany: "{count} حواسيب",
    computersNone: "لا حاسوب مفعّل",
    lastSeen: "شوهد {ago}",
    manage: "إدارة",
    close: "إغلاق",
    openClient: "صفحة الزبون",
    sections: { access: "منح الوصول", stop: "إنهاء", sanction: "عقوبات" },
    actions: {
      gift: { label: "منح مدى الحياة مجانا", hint: "رخصة دائمة ممنوحة. لا تُحسب ضمن المحصّل ويمكن إلغاؤها في أي وقت.", confirm: "منح مدى الحياة" },
      grant: { label: "منح صيغة", hint: "صيغة دُفعت خارج الموقع، نقدا أو بتحويل. تُضاف المدة إلى نهاية الرخصة الحالية.", confirm: "منح الصيغة" },
      extend: { label: "تمديد", hint: "أيام تضاف إلى النهاية، أو ابتداء من اليوم إن كانت قد مضت. التجربة المنتهية تعود تجربة.", confirm: "تمديد" },
      stop_trial: { label: "إيقاف التجربة", hint: "تنتهي التجربة الآن: يصير البرنامج للقراءة فقط. لا يُمحى شيء.", confirm: "إيقاف التجربة" },
      cancel: { label: "إلغاء الرخصة", hint: "تنتهي الآن دون مهلة، ولو كانت مدى الحياة: يصير البرنامج للقراءة فقط. يمكن للمحل دفع رخصة لإعادة فتحه.", confirm: "إلغاء الرخصة" },
      suspend: { label: "تعليق", hint: "للقراءة فقط حتى تعيد تفعيله. لا يُمحى شيء ولا تتغير التواريخ.", confirm: "تعليق" },
      reactivate: { label: "إعادة التفعيل", hint: "يُرفع التعليق: تعود الرخصة كما كانت.", confirm: "إعادة التفعيل" },
      ban: { label: "حظر", hint: "معلّق، ولا يمكن لأي حاسوب جديد تفعيله، ولا يمكن لحواسيبه فتح أي محل آخر.", confirm: "حظر" },
      unban: { label: "رفع الحظر", hint: "يستعيد المحل رخصته كما كانت قبل الحظر.", confirm: "رفع الحظر" },
    },
    reason: "السبب، يُحفظ في السجل",
    days: "الأيام",
    plan: "الصيغة",
    planNames: { annual: "سنوية", semiannual: "ستة أشهر", perpetual: "دائمة، مدفوعة" },
    cancelAction: "إلغاء",
    done: "تم. سيطبّقه البرنامج عند فحصه التالي.",
    errors: {
      banned: "هذا المحل محظور: ارفع الحظر أولا.",
      already: "هذا هو الحال بالفعل.",
      perpetual: "الرخصة الدائمة ليست لها نهاية تُحرّك.",
      no_licence: "ليست لهذا المحل رخصة بعد.",
      not_found: "المحل غير موجود.",
      not_saved: "لم يُحفظ، أعد المحاولة.",
      invalid: "تحقق من الحقول: يجب أن يتكون السبب من 4 أحرف على الأقل.",
      failed: "لا رد، تحقق من الاتصال.",
    },
  },
};

export const growthCopy: Record<AdminLanguage, GrowthCopy> = { fr, en, ar };

/* Payment apps are brands: the same name in every language. */
export const paymentAppNames: Record<string, string> = {
  bankily: "Bankily",
  masrvi: "Masrvi",
  bimbank: "BimBank",
  sedad: "SEDAD",
  click: "Click",
};
