import type { AdminLanguage } from "./copy";

/*
 * The words of the payments pages: every payment, one payment, and what
 * happened to them, in the three admin languages. Kept beside copy.ts with
 * its rule: French is the reference and the other two must match its shape.
 * {amount}, {date}, {name} and the like are filled in by the page.
 */
const fr = {
  title: "Paiements",
  intro: "Tous les paiements des propriétaires : ceux à traiter, l'historique complet avec le détail de chacun, et tout ce qui leur est arrivé.",
  figures: {
    month: "Encaissé ce mois-ci",
    monthSub: "{count} paiements confirmés",
    all: "Encaissé depuis le début",
    allSub: "au prix de ce qui a été acheté",
    toHandle: "À traiter",
    toHandleSub: "en attente ou à vérifier",
    refunds: "À rembourser",
    refundsSub: "{count} propriétaires ont trop payé",
  },
  views: { handle: "À traiter", all: "Tous les paiements", activity: "Activité" },
  filters: {
    all: "Tous",
    pending: "En attente",
    confirmed: "Confirmés",
    refund: "À rembourser",
    refused: "Refusés",
    undone: "Annulés",
  } as Record<string, string>,
  search: "Commerce, référence ou numéro du paiement",
  searchButton: "Chercher",
  clear: "Effacer",
  empty: "Aucun paiement pour l'instant.",
  emptyFilter: "Aucun paiement ne correspond.",
  showing: "Les {count} paiements les plus récents.",
  states: {
    pending: "En attente d'une personne",
    confirmed_auto: "Confirmé automatiquement, à vérifier",
    confirmed_auto_checked: "Confirmé automatiquement, vérifié",
    confirmed: "Confirmé par l'équipe",
    rejected_auto: "Refusé automatiquement",
    rejected_manual: "Rejeté par l'équipe",
    undone: "Annulé par l'équipe",
  } as Record<string, string>,
  row: {
    sent: "Envoyé {amount}",
    price: "prix {amount}",
    notRead: "montant non lu",
    owed: "À rembourser : {amount}",
    refunded: "Remboursé : {amount}",
    bySerial: "avec le numéro de série",
    byAccount: "depuis le compte",
    open: "Détail",
  },
  detail: {
    back: "Tous les paiements",
    notFound: "Ce paiement n'existe pas.",
    shop: "Commerce",
    received: "Reçu le",
    state: "État",
    plan: "Durée",
    planFromAmount: "déduite du montant",
    planChosen: "choisie par le propriétaire",
    price: "Prix",
    sent: "Envoyé",
    app: "Application",
    paidWith: "Payé",
    reference: "Transaction",
    readDate: "Date sur la capture",
    recipient: "Envoyé au numéro",
    decidedBy: "Décidé par",
    reason: "Raison",
    none: "aucune",
    automatic: "automatique",
    screenshot: "La capture",
    screenshotAlt: "Capture du paiement",
    noScreenshot: "Capture introuvable.",
    checksTitle: "Vérification de la capture",
    checksPassed: "Tout correspondait : le numéro d'OUAQT, la date du jour et le montant.",
    checksNotRead: "La capture n'a pas été lue : une personne doit la regarder.",
    decideTitle: "Décider",
    refundTitle: "Remboursement",
    refundIntro: "Le propriétaire a envoyé {sent} ; le prix de ce qu'il a acheté est {price}. Il attend {amount}. Renvoyez-les-lui, puis notez-le ici.",
    refundIntroRefused: "Le propriétaire a envoyé {sent}, moins que le prix le plus bas : rien n'a été acheté. Il attend {amount}. Renvoyez-les-lui, puis notez-le ici.",
    refundWaiting: "pas encore renvoyé",
    refundDone: "Remboursé : {amount}, le {date}, par {name}.",
    activityTitle: "Historique de ce paiement",
  },
  refund: {
    button: "Marquer comme remboursé ({amount})",
    confirm: "Vous avez bien renvoyé {amount} au propriétaire ?",
    yes: "Oui, c'est fait",
    no: "Pas encore",
    saving: "Un instant…",
    done: "Remboursement noté.",
    failed: "Pas enregistré. Réessayez.",
  },
  checks: {
    not_receipt: "L'image n'est pas la confirmation d'un transfert.",
    reference_used: "Ce numéro de transaction ({found}) a déjà servi.",
    image_used: "Cette capture a déjà été envoyée.",
    wrong_amount: "Montant {found}, attendu {expected}.",
    amount_too_low: "Montant {found}, moins que le prix le plus bas ({expected}).",
    amount_unread: "Montant illisible (attendu {expected}).",
    wrong_recipient: "Envoyé au {found}, pas au numéro d'OUAQT ({expected}).",
    recipient_unread: "Destinataire illisible (attendu {expected}).",
    wrong_date: "Capture du {found}, pas d'aujourd'hui.",
    date_unread: "Date illisible.",
  } as Record<string, string>,
  activity: {
    empty: "Rien pour l'instant.",
    actions: {
      submitted: "Capture reçue",
      pending_confirmation: "Capture reçue, en attente d'une personne",
      rejected_auto: "Capture refusée automatiquement",
      confirmed_auto: "Confirmé automatiquement",
      confirmed: "Confirmé par l'équipe",
      rejected_manual: "Rejeté par l'équipe",
      auto_confirmation_kept: "Confirmation automatique vérifiée",
      auto_confirmation_undone: "Confirmation automatique annulée",
      refunded: "Remboursement envoyé",
      licence_opened: "Licence ouverte",
    } as Record<string, string>,
    owed: "{amount} à rembourser",
    until: "jusqu'au {date}",
    system: "automatique",
    open: "Voir le paiement",
  },
};

export type PaymentsCopy = typeof fr;

const en: PaymentsCopy = {
  title: "Payments",
  intro: "Every owner payment: the ones to handle, the full history with the details of each, and everything that happened to them.",
  figures: {
    month: "Received this month",
    monthSub: "{count} confirmed payments",
    all: "Received since the start",
    allSub: "at the price of what was bought",
    toHandle: "To handle",
    toHandleSub: "waiting or to check",
    refunds: "To refund",
    refundsSub: "{count} owners paid too much",
  },
  views: { handle: "To handle", all: "All payments", activity: "Activity" },
  filters: {
    all: "All",
    pending: "Waiting",
    confirmed: "Confirmed",
    refund: "To refund",
    refused: "Refused",
    undone: "Undone",
  } as Record<string, string>,
  search: "Shop, reference or payment number",
  searchButton: "Search",
  clear: "Clear",
  empty: "No payments yet.",
  emptyFilter: "No payment matches.",
  showing: "The {count} most recent payments.",
  states: {
    pending: "Waiting for a person",
    confirmed_auto: "Confirmed automatically, to check",
    confirmed_auto_checked: "Confirmed automatically, checked",
    confirmed: "Confirmed by staff",
    rejected_auto: "Refused automatically",
    rejected_manual: "Rejected by staff",
    undone: "Undone by staff",
  } as Record<string, string>,
  row: {
    sent: "Sent {amount}",
    price: "price {amount}",
    notRead: "amount not read",
    owed: "To refund: {amount}",
    refunded: "Refunded: {amount}",
    bySerial: "with the serial number",
    byAccount: "from the account",
    open: "Details",
  },
  detail: {
    back: "All payments",
    notFound: "This payment does not exist.",
    shop: "Shop",
    received: "Received",
    state: "State",
    plan: "Length",
    planFromAmount: "read from the amount",
    planChosen: "chosen by the owner",
    price: "Price",
    sent: "Sent",
    app: "App",
    paidWith: "Paid",
    reference: "Transaction",
    readDate: "Date on the screenshot",
    recipient: "Sent to",
    decidedBy: "Decided by",
    reason: "Reason",
    none: "none",
    automatic: "automatic",
    screenshot: "The screenshot",
    screenshotAlt: "Payment screenshot",
    noScreenshot: "Screenshot not found.",
    checksTitle: "Screenshot check",
    checksPassed: "Everything matched: OUAQT's number, today's date and the amount.",
    checksNotRead: "The screenshot was not read: a person has to look at it.",
    decideTitle: "Decide",
    refundTitle: "Refund",
    refundIntro: "The owner sent {sent}; the price of what was bought is {price}. They are waiting for {amount}. Send it back, then note it here.",
    refundIntroRefused: "The owner sent {sent}, less than the lowest price: nothing was bought. They are waiting for {amount}. Send it back, then note it here.",
    refundWaiting: "not sent back yet",
    refundDone: "Refunded: {amount}, on {date}, by {name}.",
    activityTitle: "This payment's history",
  },
  refund: {
    button: "Mark as refunded ({amount})",
    confirm: "Have you sent {amount} back to the owner?",
    yes: "Yes, done",
    no: "Not yet",
    saving: "One moment…",
    done: "Refund noted.",
    failed: "Not saved. Try again.",
  },
  checks: {
    not_receipt: "The image is not a transfer confirmation.",
    reference_used: "This transaction number ({found}) was already used.",
    image_used: "This screenshot was already sent.",
    wrong_amount: "Amount {found}, expected {expected}.",
    amount_too_low: "Amount {found}, less than the lowest price ({expected}).",
    amount_unread: "Amount unreadable (expected {expected}).",
    wrong_recipient: "Sent to {found}, not OUAQT's number ({expected}).",
    recipient_unread: "Recipient unreadable (expected {expected}).",
    wrong_date: "Screenshot from {found}, not today.",
    date_unread: "Date unreadable.",
  } as Record<string, string>,
  activity: {
    empty: "Nothing yet.",
    actions: {
      submitted: "Screenshot received",
      pending_confirmation: "Screenshot received, waiting for a person",
      rejected_auto: "Screenshot refused automatically",
      confirmed_auto: "Confirmed automatically",
      confirmed: "Confirmed by staff",
      rejected_manual: "Rejected by staff",
      auto_confirmation_kept: "Automatic confirmation checked",
      auto_confirmation_undone: "Automatic confirmation undone",
      refunded: "Refund sent",
      licence_opened: "Licence opened",
    } as Record<string, string>,
    owed: "{amount} to refund",
    until: "until {date}",
    system: "automatic",
    open: "See the payment",
  },
};

const ar: PaymentsCopy = {
  title: "المدفوعات",
  intro: "كل مدفوعات الملاك: ما يجب معالجته، والسجل الكامل مع تفاصيل كل دفعة، وكل ما حدث لها.",
  figures: {
    month: "المحصّل هذا الشهر",
    monthSub: "{count} دفعات مؤكدة",
    all: "المحصّل منذ البداية",
    allSub: "بسعر ما تم شراؤه",
    toHandle: "للمعالجة",
    toHandleSub: "في الانتظار أو للتحقق",
    refunds: "للاسترجاع",
    refundsSub: "{count} ملاك دفعوا أكثر من اللازم",
  },
  views: { handle: "للمعالجة", all: "كل المدفوعات", activity: "النشاط" },
  filters: {
    all: "الكل",
    pending: "في الانتظار",
    confirmed: "مؤكدة",
    refund: "للاسترجاع",
    refused: "مرفوضة",
    undone: "ملغاة",
  } as Record<string, string>,
  search: "المحل أو المرجع أو رقم الدفعة",
  searchButton: "بحث",
  clear: "مسح",
  empty: "لا توجد مدفوعات بعد.",
  emptyFilter: "لا توجد دفعة مطابقة.",
  showing: "أحدث {count} دفعة.",
  states: {
    pending: "في انتظار شخص",
    confirmed_auto: "مؤكدة تلقائيا، للتحقق",
    confirmed_auto_checked: "مؤكدة تلقائيا، تم التحقق",
    confirmed: "أكدها الفريق",
    rejected_auto: "مرفوضة تلقائيا",
    rejected_manual: "رفضها الفريق",
    undone: "ألغاها الفريق",
  } as Record<string, string>,
  row: {
    sent: "أُرسل {amount}",
    price: "السعر {amount}",
    notRead: "المبلغ غير مقروء",
    owed: "للاسترجاع: {amount}",
    refunded: "تم الاسترجاع: {amount}",
    bySerial: "بالرقم التسلسلي",
    byAccount: "من الحساب",
    open: "التفاصيل",
  },
  detail: {
    back: "كل المدفوعات",
    notFound: "هذه الدفعة غير موجودة.",
    shop: "المحل",
    received: "استُلمت في",
    state: "الحالة",
    plan: "المدة",
    planFromAmount: "مستنتجة من المبلغ",
    planChosen: "اختارها المالك",
    price: "السعر",
    sent: "المرسل",
    app: "التطبيق",
    paidWith: "الدفع",
    reference: "رقم العملية",
    readDate: "التاريخ في الصورة",
    recipient: "أرسل إلى الرقم",
    decidedBy: "قرره",
    reason: "السبب",
    none: "لا شيء",
    automatic: "تلقائي",
    screenshot: "الصورة",
    screenshotAlt: "صورة شاشة الدفع",
    noScreenshot: "الصورة غير موجودة.",
    checksTitle: "التحقق من الصورة",
    checksPassed: "كل شيء مطابق: رقم OUAQT، تاريخ اليوم والمبلغ.",
    checksNotRead: "لم تُقرأ الصورة: يجب أن ينظر إليها شخص.",
    decideTitle: "القرار",
    refundTitle: "الاسترجاع",
    refundIntro: "أرسل المالك {sent}، وسعر ما اشتراه {price}. ينتظر {amount}. أعدها إليه، ثم سجّل ذلك هنا.",
    refundIntroRefused: "أرسل المالك {sent}، وهو أقل من أدنى سعر: لم يُشترَ شيء. ينتظر {amount}. أعدها إليه، ثم سجّل ذلك هنا.",
    refundWaiting: "لم يُرجع بعد",
    refundDone: "تم الاسترجاع: {amount}، في {date}، بواسطة {name}.",
    activityTitle: "سجل هذه الدفعة",
  },
  refund: {
    button: "تسجيل الاسترجاع ({amount})",
    confirm: "هل أعدت {amount} إلى المالك؟",
    yes: "نعم، تم",
    no: "ليس بعد",
    saving: "لحظة…",
    done: "تم تسجيل الاسترجاع.",
    failed: "لم يُحفظ. أعد المحاولة.",
  },
  checks: {
    not_receipt: "الصورة ليست تأكيد تحويل.",
    reference_used: "رقم العملية هذا ({found}) استُعمل من قبل.",
    image_used: "هذه الصورة أُرسلت من قبل.",
    wrong_amount: "المبلغ {found}، والمتوقع {expected}.",
    amount_too_low: "المبلغ {found}، أقل من أدنى سعر ({expected}).",
    amount_unread: "المبلغ غير مقروء (المتوقع {expected}).",
    wrong_recipient: "أرسل إلى {found}، لا إلى رقم OUAQT ({expected}).",
    recipient_unread: "المستلم غير مقروء (المتوقع {expected}).",
    wrong_date: "صورة بتاريخ {found}، ليس اليوم.",
    date_unread: "التاريخ غير مقروء.",
  } as Record<string, string>,
  activity: {
    empty: "لا شيء بعد.",
    actions: {
      submitted: "استُلمت الصورة",
      pending_confirmation: "استُلمت الصورة، في انتظار شخص",
      rejected_auto: "رُفضت الصورة تلقائيا",
      confirmed_auto: "أُكدت تلقائيا",
      confirmed: "أكدها الفريق",
      rejected_manual: "رفضها الفريق",
      auto_confirmation_kept: "تم التحقق من التأكيد التلقائي",
      auto_confirmation_undone: "أُلغي التأكيد التلقائي",
      refunded: "أُرسل الاسترجاع",
      licence_opened: "فُتحت الرخصة",
    } as Record<string, string>,
    owed: "{amount} للاسترجاع",
    until: "حتى {date}",
    system: "تلقائي",
    open: "عرض الدفعة",
  },
};

export const paymentsCopy: Record<AdminLanguage, PaymentsCopy> = { fr, en, ar };
