/*
 * Every word the admin area says, in French, English and Arabic.
 *
 * French is the reference: the other two follow its shape, which the types
 * below enforce, so a key missing in one language fails the build rather than
 * showing a blank to staff.
 *
 * Placeholders in braces are filled with fill() from lib/utils. Nothing here
 * is a function, because the client components receive their part of it as
 * props, and only plain text crosses from the server to the browser.
 *
 * The settings' own descriptions come from the database and are not
 * translated here: they are notes staff wrote about each key, not interface.
 */

export const adminLanguages = ["fr", "en", "ar"] as const;
export type AdminLanguage = (typeof adminLanguages)[number];

/* Each language is always named in itself, whichever one is showing. */
export const languageNames: Record<AdminLanguage, string> = {
  fr: "Français",
  en: "English",
  ar: "العربية",
};

const fr = {
  brand: "OUAQT admin",
  noDatabase: "Aucune base de données configurée.",
  staffFallback: "équipe",
  openStaff: "Test, sans connexion",
  openBanner:
    "Administration de test, ouverte sans connexion. Elle se ferme d'elle-même en production et sur toute autre base de données.",

  nav: {
    overview: "Vue d'ensemble",
    stats: "Statistiques",
    payments: "Paiements",
    clients: "Clients",
    control: "Contrôle",
    devices: "Postes",
    codes: "Codes",
    funnel: "Parcours",
    trials: "Essais",
    requests: "Demandes",
    settings: "Réglages",
    aiCost: "Coût IA",
    staff: "Équipe",
    reps: "Commerciaux",
  },

  navGroups: { follow: "Suivi", setup: "Configuration" },

  /* The words for values the database stores in English. */
  packs: {
    pharmacy: "Pharmacie",
    bakery: "Boulangerie",
    restaurant: "Restaurant",
    warehouse: "Dépôt",
    shop: "Boutique",
    hotel: "Hôtel",
    transport: "Transport",
    general: "Autre activité",
  } as Record<string, string>,
  plans: {
    trial: "Essai",
    annual: "Annuelle",
    semiannual: "Semestrielle",
    quarterly: "Trimestrielle",
    perpetual: "Définitive",
    extra_device: "Poste supplémentaire",
    setup_visit: "Visite d'installation",
  } as Record<string, string>,
  statuses: {
    trial: "Essai",
    active: "Active",
    expired_trial: "Essai terminé",
    renewal_due: "À renouveler",
    expired: "Expirée",
    suspended: "Suspendue",
  } as Record<string, string>,
  roles: { main: "Principal", secondary: "Secondaire" } as Record<string, string>,

  signIn: {
    email: "E-mail ou identifiant",
    password: "Mot de passe",
    continue: "Continuer",
    scan: "Scannez ce code avec une application d'authentification, puis tapez le code à six chiffres qu'elle affiche.",
    orKey: "Ou tapez cette clé :",
    checking: "Vérification…",
    setupTitle: "Première connexion : reliez votre téléphone",
    step1: "Installez sur votre téléphone une application d'authentification gratuite : Google Authenticator, Microsoft Authenticator ou Authy.",
    step2: "Dans l'application, touchez « + », puis « Scanner un code QR », et visez ce code.",
    step3: "L'application affiche OUAQT avec un code à six chiffres qui change toutes les 30 secondes. Tapez le code affiché ci-dessous.",
    codeHint: "Le code est affiché par l'application d'authentification de votre téléphone, sous OUAQT. Il change toutes les 30 secondes.",
    retry: "Réessayer",
    code: "Code à six chiffres",
    signIn: "Se connecter",
    notStaff:
      "Ce compte n'est pas dans la liste de l'équipe. Si vous êtes commerçant, votre logiciel est dans votre propre compte.",
    signOut: "Se déconnecter",
    wrong: "Identifiant ou mot de passe incorrect.",
    setupFailed: "Impossible de lancer la configuration de l'authentificateur.",
    noFactor: "Aucun authentificateur à vérifier.",
    challengeFailed: "Impossible de demander un code.",
    badCode: "Ce code n'a pas été accepté.",
  },

  payments: {
    title: "Paiements à confirmer",
    empty: "Rien à confirmer. Les paiements arrivent ici dès qu'un propriétaire envoie une capture.",
    launch: "lancement",
    expected: "Attendu",
    plan: "Formule",
    app: "Application",
    reference: "Référence",
    none: "aucune",
    received: "Reçu le",
    readAmount: "Montant lu",
    readDate: "Date lue",
    readRecipient: "Envoyé au",
    notRead: "Capture non lue par l'IA : lisez le montant, la date et la référence sur l'image.",
    screenshotAlt: "Capture du transfert",
    noScreenshot: "Capture introuvable.",
    reasonLabel: "Raison, si vous rejetez",
    reasonNeeded: "Dites pourquoi : le propriétaire le verra.",
    confirm: "Confirmer",
    reject: "Rejeter",
    confirmed: "Confirmé",
    rejected: "Rejeté",
    failed: "Pas enregistré.",
    automaticTitle: "Confirmés automatiquement, à vérifier",
    automaticIntro: "La capture a été lue et tout correspondait, donc la licence s'est ouverte tout de suite. Regardez l'image : gardez le paiement, ou annulez-le si la capture n'est pas ce qu'elle paraît. Annuler remet la licence comme avant.",
    keep: "C'est bon",
    kept: "Gardé",
    undo: "Annuler le paiement",
    undoReasonLabel: "Raison, si vous annulez",
  },

  clients: {
    title: "Clients",
    search: "Nom du commerce ou numéro de série",
    searchButton: "Chercher",
    nothingFound: "Rien trouvé.",
    none: "Aucun client pour l'instant.",
    noLicence: "aucune licence",
    launch: "lancement",
    all: "Tous",
    seen: "vu {ago}",
    neverSeen: "jamais connecté",
    shown: "{shown} sur {total}",
    searchingFor: "Résultats pour « {query} »",
    clearSearch: "Effacer la recherche",
  },

  devices: {
    title: "Postes",
    none: "Aucun ordinateur activé pour l'instant.",
    unnamed: "sans nom",
    freed: "Libéré",
    seen: "Vu le {date}",
    reason: "Raison",
    release: "Libérer",
    reasonNeeded: "Dites pourquoi : cela reste écrit.",
    notFreed: "Pas libéré.",
  },

  search: {
    placeholder: "Chercher un client : nom, téléphone, numéro de série, code du poste",
    none: "Aucun client ne correspond.",
    all: "Voir tous les résultats ({count})",
    searching: "Recherche…",
    by: "par {what}",
    matched: {
      name: "nom",
      phone: "téléphone",
      serial: "numéro de série",
      device: "code du poste",
      address: "adresse",
      id: "identifiant",
    } as Record<string, string>,
  },

  overview: {
    title: "Vue d'ensemble",
    live: "En direct · {time}",
    refresh: "Actualiser",
    allClear: "Rien n'attend de réponse.",
    todo: {
      payments: "paiements à confirmer",
      review: "paiements automatiques à vérifier",
      codes: "numéros de série à renvoyer",
      requests: "demandes de propriétaires",
    },
    kpi: {
      clients: "Clients",
      clientsSub: "+{count} ces 7 derniers jours",
      online: "Logiciels en ligne",
      onlineSub: "{shops} commerces · {total} ordinateurs activés",
      paying: "Licences payantes",
      payingSub: "{amount} encaissés ce mois",
      visitors: "Dans le Builder maintenant",
      visitorsSub: "{count} aujourd'hui",
      site: "Visiteurs du site aujourd'hui",
      siteSub: "{now} en ce moment · {week} sur 7 jours",
      downloads: "Téléchargements",
      downloadsSub: "{today} aujourd'hui · Windows {windows} · Mac {mac}",
    },
    statusTitle: "Statut des clients",
    statusTotal: "{count} commerces",
    noLicence: "Sans licence",
    tiles: {
      total: "Commerces",
      trial: "En essai",
      active: "Licence active",
      renewal_due: "À renouveler",
      expired: "Expirés, en lecture seule",
      suspended: "Suspendus",
    },
    appsTitle: "Logiciels installés",
    appsIntro: "Chaque logiciel se signale à son démarrage, puis toutes les 3 heures quand il a internet.",
    presence: {
      now: "En ligne, moins de 3 h",
      today: "Vus dans les 24 h",
      week: "Vus dans les 7 jours",
      older: "Inactifs depuis plus de 7 jours",
    },
    platforms: "Windows {windows} · Mac {mac}",
    activityTitle: "Activité",
    series: { shops: "Nouveaux clients", visitors: "Visiteurs du créateur", activations: "Ordinateurs activés" },
    range: { d7: "7 jours", d30: "30 jours" },
    periodTotal: "sur {days} jours",
    chartEmpty: "Rien sur cette période.",
    appsListTitle: "Logiciels, du plus récent",
    filters: { now: "En ligne", today: "24 h", week: "7 jours", all: "Tous" },
    noApps: "Aucun logiciel dans cette période.",
    endingTitle: "Échéances, 7 jours",
    endingNone: "Aucun essai ni licence ne se termine cette semaine.",
    endsToday: "aujourd'hui",
    endsIn: "{days} j",
    historyTitle: "Dernières actions",
    historyNone: "Rien pour l'instant.",
    automatic: "automatique",
    seeAll: "Tout voir",
    systemTitle: "Santé du système",
    signingOk: "Les licences sont signées.",
    signingMissing: "Clé de signature absente : aucun logiciel ne peut s'activer ni se renouveler.",
    aiUse: "IA, 24 heures : {used} appels sur {limit}.",
    aiNear: "IA, 24 heures : {used} appels sur {limit}. Au-delà, une personne lit les phrases et les captures.",
    autoConfirmOn: "Les paiements dont la capture correspond se confirment seuls.",
    autoConfirmOff: "Chaque paiement attend une personne.",
    downloads: "Téléchargements : Windows {windows}/{total} métiers, Mac {mac}/{total}.",
  },

  client: {
    back: "Tous les clients",
    notFound: "Ce commerce n'existe pas, ou plus.",
    since: "Client depuis le {date}",
    launch: "client de lancement",
    contactTitle: "Contact",
    phone: "Téléphone",
    email: "E-mail",
    noContact: "Aucun contact enregistré.",
    whatsapp: "Écrire sur WhatsApp",
    licenceTitle: "Licence",
    plan: "Formule",
    status: "État",
    starts: "Début",
    ends: "Fin",
    noEnd: "sans fin",
    notStarted: "commence à la première activation",
    daysLeft: "{days} jours restants",
    daysLeftShort: "{days} j restants",
    noLicence: "Ce commerce n'a pas de licence.",
    controlsTitle: "Contrôle",
    suspend: "Suspendre le logiciel",
    suspendIntro:
      "Pour un manquement aux conditions. Le logiciel passe en lecture seule à sa prochaine connexion : en 3 heures au plus s'il a internet, sinon dès qu'il en retrouve. Le propriétaire garde toutes ses données, peut les consulter et les exporter, et un message lui demande de vous contacter. Rien n'est effacé.",
    suspendReason: "Le manquement, en quelques mots",
    suspendConfirm: "Suspendre {name}",
    suspendedDone: "Suspendu. Le logiciel le saura à sa prochaine connexion.",
    reactivate: "Réactiver le logiciel",
    reactivateIntro: "Le logiciel repart comme avant à sa prochaine connexion, avec les dates qu'il avait.",
    reactivateReason: "Pourquoi maintenant",
    reactivateConfirm: "Réactiver {name}",
    reactivatedDone: "Réactivé. Le logiciel le saura à sa prochaine connexion.",
    grant: "Renouveler ou activer",
    setEnd: "Changer la date de fin",
    setEndIntro: "Pour prolonger un essai, offrir des jours ou corriger une date. Le logiciel suit la nouvelle date à sa prochaine connexion. Un essai qui n'avait pas commencé commence aujourd'hui.",
    setEndDate: "Nouvelle date de fin",
    setEndReason: "Pourquoi",
    setEndConfirm: "Enregistrer la date",
    setEndDone: "Nouvelle date de fin : {date}.",
    end: "Mettre fin à l'abonnement",
    endIntro: "La licence se termine aujourd'hui. Un essai passe tout de suite en lecture seule. Une licence payée rappelle le renouvellement chaque jour pendant {grace} jours, puis passe en lecture seule. Pour tout arrêter immédiatement, suspendez plutôt le logiciel.",
    endReason: "Pourquoi",
    endConfirm: "Mettre fin à l'abonnement de {name}",
    endDone: "L'abonnement se termine aujourd'hui. Le logiciel le saura à sa prochaine connexion.",
    grantIntro:
      "Pour un paiement reçu hors du site, en espèces ou par virement. Le temps s'ajoute à la date de fin actuelle. Un logiciel suspendu le reste jusqu'à ce que vous le réactiviez.",
    grantPlan: "Formule",
    grantReason: "Comment il a payé",
    grantConfirm: "Activer",
    grantedUntil: "Activée jusqu'au {date}.",
    grantedForever: "Activée, sans date de fin.",
    reasonNeeded: "Écrivez la raison : elle reste dans l'historique.",
    failed: "Rien n'a été changé. Réessayez.",
    cancel: "Annuler",
    devicesTitle: "Ordinateurs",
    paymentsTitle: "Paiements",
    noPayments: "Aucun paiement.",
    paymentStatuses: {
      submitted: "En attente",
      pending_confirmation: "En attente",
      confirmed: "Confirmé",
      rejected_auto: "Refusé automatiquement",
      rejected_manual: "Rejeté",
    } as Record<string, string>,
    historyTitle: "Historique",
    noHistory: "Rien pour l'instant.",
  },

  /* What the trail records, as the overview and a client's page say it. */
  actions: {
    end_date_set: "Date de fin changée",
    subscription_ended: "Abonnement terminé",
    activated: "Licence activée",
    confirmed: "Paiement confirmé",
    confirmed_auto: "Paiement confirmé automatiquement",
    rejected_manual: "Paiement rejeté",
    auto_confirmation_kept: "Paiement automatique vérifié",
    auto_confirmation_undone: "Paiement automatique annulé",
    released_by_owner: "Ordinateur libéré par le propriétaire",
    released_by_staff: "Ordinateur libéré par l'équipe",
    renewal_code_generated: "Code de renouvellement donné",
    trial_started: "Essai commencé",
    trial_refused: "Essai refusé",
    trial_granted_by_hand: "Essai donné à la main",
    trial_ended_for_test: "Essai terminé pour un test",
    suspended: "Logiciel suspendu",
    suspension_lifted: "Logiciel réactivé",
    "device:activated": "Ordinateur activé",
    "device:reactivated": "Ordinateur activé à nouveau",
    test_mode_opened: "Mode test ouvert",
    granted_by_hand: "Licence activée à la main",
    changed: "Réglage modifié",
    configuration_code_sent_by_hand: "Numéro de série renvoyé",
    configuration_code_revived: "Numéro de série réactivé",
    staff_added: "Membre de l'équipe ajouté",
    staff_password_set: "Mot de passe d'un membre changé",
    staff_factor_reset: "Authentificateur d'un membre effacé",
    staff_removed: "Membre retiré de l'équipe",
    "representative:created": "Commercial ajouté",
    "representative:updated": "Bonus d'un commercial modifié",
    "representative:deactivated": "Commercial désactivé",
    "representative:reactivated": "Commercial réactivé",
    "representative:paid": "Bonus versé à un commercial",
    representative_set: "Commercial attribué à un commerce",
    gifted_for_life: "Licence offerte à vie",
    cancelled: "Licence annulée",
    extended: "Licence prolongée",
    banned: "Commerce banni",
    unbanned: "Bannissement levé",
  } as Record<string, string>,

  staff: {
    title: "Équipe",
    intro: "Les personnes qui peuvent ouvrir cette administration. Chacune se connecte avec son identifiant, son mot de passe, puis le code à six chiffres de son téléphone.",
    you: "vous",
    since: "depuis le {date}",
    factorReady: "authentificateur prêt",
    factorMissing: "code QR à la première connexion",
    formTitle: "Ajouter une personne, ou changer un mot de passe",
    formIntro: "Un identifiant déjà dans l'équipe reçoit simplement le nouveau mot de passe.",
    login: "Identifiant de connexion",
    loginHint: "Ce que la personne tapera pour se connecter : son adresse e-mail, ou le nom de votre choix.",
    name: "Nom affiché (facultatif)",
    password: "Mot de passe",
    passwordHint: "12 caractères au moins.",
    again: "Le même mot de passe",
    save: "Enregistrer",
    added: "C'est fait. {login} peut se connecter à l'administration. À la première connexion, un code QR s'affiche : scannez-le avec une application d'authentification.",
    passwordSet: "Nouveau mot de passe enregistré pour {login}.",
    resetFactor: "Téléphone perdu : refaire le code QR",
    factorReset: "C'est fait. À sa prochaine connexion, un nouveau code QR s'affichera.",
    remove: "Retirer de l'équipe",
    removeConfirm: "Retirer {login} ? Son identifiant n'ouvrira plus l'administration.",
    removeYes: "Oui, retirer",
    removed: "Retiré de l'équipe.",
    cancel: "Annuler",
    errors: {
      bad_login: "Écrivez un identifiant, de 100 caractères au plus.",
      too_short: "Le mot de passe doit avoir au moins 12 caractères.",
      only_digits: "Le mot de passe ne peut pas être fait que de chiffres.",
      one_character: "Le mot de passe ne peut pas répéter un seul caractère.",
      mismatch: "Les deux mots de passe ne sont pas les mêmes.",
      yourself: "Vous ne pouvez pas vous retirer vous-même.",
      open_preview: "Sur un lien de test ouvert, l'équipe ne peut pas être modifiée. Faites-le depuis votre ordinateur, ou une fois connecté.",
      failed: "Rien n'a été enregistré. Réessayez.",
    } as Record<string, string>,
  },

  codes: {
    title: "Codes de renouvellement",
    intro:
      "Le propriétaire lit le code affiché par son logiciel. Vous lui lisez celui-ci. Il le tape sans internet et son logiciel repart.",
    shop: "Le commerce",
    deviceCode: "Le code affiché par son logiciel",
    newEnd: "Nouvelle date de fin",
    generate: "Générer le code",
    notGenerated: "Pas généré.",
    readToOwner: "À lire au propriétaire",
    copy: "Copier",
    copied: "Copié",
    recent: "Derniers codes",
    until: "jusqu'au {date}",
  },

  funnel: {
    title: "Parcours",
    nobody: "Personne n'a encore commencé.",
    step: "Étape",
    reached: "Arrivés",
    perHundred: "Sur cent",
    steps: ["Votre commerce", "Questions", "Produits et employés", "Numéro de série"],
    byPack: "Par activité",
    byDevice: "Téléphone ou ordinateur",
    noPack: "sans activité",
    unknown: "inconnu",
  },

  requests: {
    title: "Ce que les propriétaires ont demandé",
    nothing: "Rien pour l'instant.",
    noPack: "sans activité",
    noQuestion: "sans question",
    leadsTitle: "Activités qui n'ont pas encore de logiciel",
    noLeads: "Personne n'a encore laissé son numéro.",
    codesTitle: "Numéros de série à renvoyer",
    codesIntro:
      "L'envoi sur WhatsApp n'est pas encore branché. Envoyez le numéro à la main avec le lien, puis marquez-le envoyé.",
    noCodes: "Aucune demande en attente.",
    expired: "expiré",
    sendOnWhatsApp: "Envoyer sur WhatsApp",
    markSent: "Marquer envoyé",
    markedSent: "Envoyé",
    revive: "Réactiver",
    revived: "Réactivé pour {days} jours.",
    reviveTitle: "Réactiver un numéro expiré",
    reviveLabel: "Le numéro, tel que le propriétaire l'a envoyé",
    reviveFailed: "Numéro introuvable.",
    actionFailed: "L'action n'a pas abouti. Réessayez.",
  },

  settings: {
    title: "Réglages",
    intro:
      "Les valeurs changent ici, jamais dans le code. Un prix vide veut dire que la page le dit, plutôt que d'inventer un chiffre.",
    testPacks: "Les métiers en test sont fermés aux clients. Ce lien les ouvre dans ce navigateur, pour les essayer.",
    testBuilder: "Tester le créateur",
    leaveTest: "Quitter le mode test",
    save: "Enregistrer",
    saved: "Enregistré",
    notJson: "Ce n'est pas une valeur valide. Un nombre s'écrit 15000, un texte entre guillemets.",
    wrongKind: "Cette valeur doit rester du même type qu'avant ({was}).",
    notSaved: "Pas enregistré.",
  },

  aiCost: {
    title: "Coût IA",
    none: "Aucun appel pour l'instant.",
    total: "{calls} appels, {tokens} jetons au total.",
    outcome: "Résultat",
    calls: "Appels",
    tokens: "Jetons",
  },

  trials: {
    title: "Essais",
    intro:
      "Un essai par commerce. Ce qui est signalé ci-dessous n'a bloqué personne : c'est une raison de regarder, pas une accusation.",
    flagged: "Possible essai répété ({count})",
    nothingFlagged: "Rien à signaler.",
    unnamed: "Sans nom",
    refused: "Refusés, à rappeler ({count})",
    nobodyRefused: "Personne.",
    refusedFallback: "Refusé",
    grantTitle: "Donner un essai",
    grantIntro:
      "Pour un ordinateur acheté d'occasion, une machine réparée que nous n'avons pas reconnue, ou toute personne que nous avons refusée à tort. Son essai démarre à sa prochaine activation.",
    all: "Tous les essais ({count})",
    shop: "Le commerce",
    choose: "Choisir",
    why: "Pourquoi",
    whyExample: "Ordinateur acheté d'occasion, vérifié par téléphone",
    grant: "Donner un essai",
    granted: "C'est fait. Son essai démarrera à la prochaine activation.",
    grantFailed: "Rien n'a été enregistré. Réessayez.",
    testEndTitle: "Tester la fin de l'essai",
    testEndIntro:
      "Seulement sur la version de test. Termine tout de suite l'essai du commerce choisi : fermez puis rouvrez le logiciel, relié à internet, et la fenêtre de fin d'essai s'affiche, avec son numéro de série et son code QR.",
    testEndButton: "Terminer l'essai maintenant",
    testEndDone: "Essai terminé. Fermez puis rouvrez le logiciel.",
    testEndNotTrial: "Ce commerce a déjà une licence payée : rien n'a été changé.",
    signals: {
      same_logo: "Même logo qu'un essai précédent",
      same_products: "Même liste de produits",
      similar_name: "Nom de commerce très proche",
      similar_address: "Adresse très proche",
    } as Record<string, string>,
    refusals: {
      same_machine: "Même ordinateur qu'un essai précédent",
      same_phone: "Même numéro de téléphone",
      same_business: "Ce commerce a déjà eu son essai",
      no_fingerprint: "Le logiciel n'a envoyé aucune empreinte de machine",
    } as Record<string, string>,
  },
};

export type AdminCopy = typeof fr;

const en: AdminCopy = {
  brand: "OUAQT admin",
  noDatabase: "No database configured.",
  staffFallback: "staff",
  openStaff: "Test, no sign-in",
  openBanner:
    "Test admin, open without signing in. It locks itself in production and on any other database.",

  nav: {
    overview: "Overview",
    stats: "Statistics",
    payments: "Payments",
    clients: "Customers",
    control: "Software control",
    devices: "Computers",
    codes: "Codes",
    funnel: "Funnel",
    trials: "Trials",
    requests: "Requests",
    settings: "Settings",
    aiCost: "AI cost",
    staff: "Team",
    reps: "Sales reps",
  },

  navGroups: { follow: "Follow-up", setup: "Setup" },

  packs: { pharmacy: "Pharmacy", bakery: "Bakery", restaurant: "Restaurant", warehouse: "Warehouse", shop: "Shop", hotel: "Hotel", transport: "Transport", general: "Other business" },
  plans: {
    trial: "Trial",
    annual: "Annual",
    semiannual: "Six months",
    quarterly: "Quarterly",
    perpetual: "Permanent",
    extra_device: "Extra computer",
    setup_visit: "Installation visit",
  },
  statuses: {
    trial: "Trial",
    active: "Active",
    expired_trial: "Trial ended",
    renewal_due: "Renewal due",
    expired: "Expired",
    suspended: "Suspended",
  },
  roles: { main: "Main", secondary: "Second" },

  signIn: {
    email: "Email or username",
    password: "Password",
    continue: "Continue",
    scan: "Scan this with an authenticator app, then type the six-digit code it shows.",
    orKey: "Or type this key:",
    checking: "Checking…",
    setupTitle: "First sign-in: link your phone",
    step1: "Install a free authenticator app on your phone: Google Authenticator, Microsoft Authenticator or Authy.",
    step2: "In the app, tap “+”, then “Scan a QR code”, and point it at this code.",
    step3: "The app shows OUAQT with a six-digit code that changes every 30 seconds. Type the code shown below.",
    codeHint: "The code is shown by the authenticator app on your phone, under OUAQT. It changes every 30 seconds.",
    retry: "Try again",
    code: "Six-digit code",
    signIn: "Sign in",
    notStaff:
      "This account is not on the staff list. If you are a shop owner, your software is on your own account page.",
    signOut: "Sign out",
    wrong: "Wrong username or password.",
    setupFailed: "Could not start setting up the authenticator.",
    noFactor: "No authenticator to check against.",
    challengeFailed: "Could not ask for a code.",
    badCode: "That code was not accepted.",
  },

  payments: {
    title: "Payments to confirm",
    empty: "Nothing to confirm. Payments arrive here as soon as an owner sends a screenshot.",
    launch: "launch",
    expected: "Expected",
    plan: "Plan",
    app: "App",
    reference: "Reference",
    none: "none",
    received: "Received",
    readAmount: "Amount read",
    readDate: "Date read",
    readRecipient: "Sent to",
    notRead: "Screenshot not read by the AI: read the amount, the date and the reference on the image.",
    screenshotAlt: "Transfer screenshot",
    noScreenshot: "Screenshot not found.",
    reasonLabel: "Reason, if you reject",
    reasonNeeded: "Say why: the owner will see it.",
    confirm: "Confirm",
    reject: "Reject",
    confirmed: "Confirmed",
    rejected: "Rejected",
    failed: "Not saved.",
    automaticTitle: "Confirmed automatically, to check",
    automaticIntro: "The screenshot was read and everything matched, so the licence opened straight away. Look at the image: keep the payment, or undo it if the screenshot is not what it seems. Undoing puts the licence back as it was.",
    keep: "Keep",
    kept: "Kept",
    undo: "Undo the payment",
    undoReasonLabel: "Reason, if you undo",
  },

  clients: {
    title: "Customers",
    search: "Shop name or serial number",
    searchButton: "Search",
    nothingFound: "Nothing found.",
    none: "No customers yet.",
    noLicence: "no licence",
    launch: "launch",
    all: "All",
    seen: "seen {ago}",
    neverSeen: "never connected",
    shown: "{shown} of {total}",
    searchingFor: "Results for “{query}”",
    clearSearch: "Clear search",
  },

  devices: {
    title: "Computers",
    none: "No computer activated yet.",
    unnamed: "unnamed",
    freed: "Released",
    seen: "Seen {date}",
    reason: "Reason",
    release: "Release",
    reasonNeeded: "Say why: it stays on record.",
    notFreed: "Not released.",
  },

  search: {
    placeholder: "Find a customer: name, phone, serial number, computer code",
    none: "No customer matches.",
    all: "See all results ({count})",
    searching: "Searching…",
    by: "by {what}",
    matched: {
      name: "name",
      phone: "phone",
      serial: "serial number",
      device: "computer code",
      address: "address",
      id: "id",
    },
  },

  overview: {
    title: "Overview",
    live: "Live · {time}",
    refresh: "Refresh",
    allClear: "Nothing is waiting for an answer.",
    todo: {
      payments: "payments to confirm",
      review: "automatic payments to check",
      codes: "serial numbers to resend",
      requests: "requests from owners",
    },
    kpi: {
      clients: "Customers",
      clientsSub: "+{count} in the last 7 days",
      online: "Software online",
      onlineSub: "{shops} shops · {total} computers activated",
      paying: "Paying licences",
      payingSub: "{amount} received this month",
      visitors: "In the Builder now",
      visitorsSub: "{count} today",
      site: "Site visitors today",
      siteSub: "{now} right now · {week} in 7 days",
      downloads: "Downloads",
      downloadsSub: "{today} today · Windows {windows} · Mac {mac}",
    },
    statusTitle: "Customer status",
    statusTotal: "{count} shops",
    noLicence: "No licence",
    tiles: {
      total: "Shops",
      trial: "On trial",
      active: "Licence active",
      renewal_due: "Renewal due",
      expired: "Expired, read only",
      suspended: "Suspended",
    },
    appsTitle: "Installed software",
    appsIntro: "Each copy checks in when it starts, then every 3 hours while it has internet.",
    presence: {
      now: "Online, under 3 h",
      today: "Seen in the last 24 h",
      week: "Seen in the last 7 days",
      older: "Inactive for over 7 days",
    },
    platforms: "Windows {windows} · Mac {mac}",
    activityTitle: "Activity",
    series: { shops: "New customers", visitors: "Builder visitors", activations: "Computers activated" },
    range: { d7: "7 days", d30: "30 days" },
    periodTotal: "over {days} days",
    chartEmpty: "Nothing in this period.",
    appsListTitle: "Software, most recent first",
    filters: { now: "Online", today: "24 h", week: "7 days", all: "All" },
    noApps: "No software in this period.",
    endingTitle: "Ending within 7 days",
    endingNone: "No trial or licence ends this week.",
    endsToday: "today",
    endsIn: "{days} d",
    historyTitle: "Latest actions",
    historyNone: "Nothing yet.",
    automatic: "automatic",
    seeAll: "See all",
    systemTitle: "System health",
    signingOk: "Licences are being signed.",
    signingMissing: "No signing key: no software can activate or renew.",
    aiUse: "AI, 24 hours: {used} calls of {limit}.",
    aiNear: "AI, 24 hours: {used} calls of {limit}. Past that, a person reads the sentences and screenshots.",
    autoConfirmOn: "Payments whose screenshot matches confirm themselves.",
    autoConfirmOff: "Every payment waits for a person.",
    downloads: "Downloads: Windows {windows}/{total} trades, Mac {mac}/{total}.",
  },

  client: {
    back: "All customers",
    notFound: "This shop does not exist, or no longer does.",
    since: "Customer since {date}",
    launch: "launch customer",
    contactTitle: "Contact",
    phone: "Phone",
    email: "Email",
    noContact: "No contact on record.",
    whatsapp: "Write on WhatsApp",
    licenceTitle: "Licence",
    plan: "Plan",
    status: "Status",
    starts: "Start",
    ends: "End",
    noEnd: "no end",
    notStarted: "starts at the first activation",
    daysLeft: "{days} days left",
    daysLeftShort: "{days} days left",
    noLicence: "This shop has no licence.",
    controlsTitle: "Control",
    suspend: "Suspend the software",
    suspendIntro:
      "For a breach of the terms. The software goes read only the next time it connects: within 3 hours if it has internet, otherwise as soon as it gets it back. The owner keeps all his data, can still read and export it, and is asked to contact you. Nothing is deleted.",
    suspendReason: "The breach, in a few words",
    suspendConfirm: "Suspend {name}",
    suspendedDone: "Suspended. The software will know the next time it connects.",
    reactivate: "Reactivate the software",
    reactivateIntro: "The software carries on as before the next time it connects, with the dates it had.",
    reactivateReason: "Why now",
    reactivateConfirm: "Reactivate {name}",
    reactivatedDone: "Reactivated. The software will know the next time it connects.",
    grant: "Renew or activate",
    setEnd: "Change the end date",
    setEndIntro: "To lengthen a trial, give days or correct a date. The software follows the new date the next time it connects. A trial that had not started starts today.",
    setEndDate: "New end date",
    setEndReason: "Why",
    setEndConfirm: "Save the date",
    setEndDone: "New end date: {date}.",
    end: "End the subscription",
    endIntro: "The licence ends today. A trial goes read only at once. A paid licence reminds the owner to renew every day for {grace} days, then goes read only. To stop everything immediately, suspend the software instead.",
    endReason: "Why",
    endConfirm: "End {name}'s subscription",
    endDone: "The subscription ends today. The software will know the next time it connects.",
    grantIntro:
      "For a payment received outside the site, in cash or by transfer. The time is added to the current end date. Suspended software stays suspended until you reactivate it.",
    grantPlan: "Plan",
    grantReason: "How he paid",
    grantConfirm: "Activate",
    grantedUntil: "Active until {date}.",
    grantedForever: "Active, with no end date.",
    reasonNeeded: "Write the reason: it stays in the history.",
    failed: "Nothing was changed. Try again.",
    cancel: "Cancel",
    devicesTitle: "Computers",
    paymentsTitle: "Payments",
    noPayments: "No payments.",
    paymentStatuses: {
      submitted: "Waiting",
      pending_confirmation: "Waiting",
      confirmed: "Confirmed",
      rejected_auto: "Refused automatically",
      rejected_manual: "Rejected",
    },
    historyTitle: "History",
    noHistory: "Nothing yet.",
  },

  actions: {
    end_date_set: "End date changed",
    subscription_ended: "Subscription ended",
    activated: "Licence activated",
    confirmed: "Payment confirmed",
    confirmed_auto: "Payment confirmed automatically",
    rejected_manual: "Payment rejected",
    auto_confirmation_kept: "Automatic payment checked",
    auto_confirmation_undone: "Automatic payment undone",
    released_by_owner: "Computer freed by the owner",
    released_by_staff: "Computer freed by staff",
    renewal_code_generated: "Renewal code given",
    trial_started: "Trial started",
    trial_refused: "Trial refused",
    trial_granted_by_hand: "Trial given by hand",
    trial_ended_for_test: "Trial ended for a test",
    suspended: "Software suspended",
    suspension_lifted: "Software reactivated",
    "device:activated": "Computer activated",
    "device:reactivated": "Computer activated again",
    test_mode_opened: "Test mode opened",
    granted_by_hand: "Licence activated by hand",
    changed: "Setting changed",
    configuration_code_sent_by_hand: "Serial number resent",
    configuration_code_revived: "Serial number revived",
    staff_added: "Team member added",
    staff_password_set: "Team member's password changed",
    staff_factor_reset: "Team member's authenticator cleared",
    staff_removed: "Team member removed",
    "representative:created": "Sales representative added",
    "representative:updated": "Representative's bonus changed",
    "representative:deactivated": "Sales representative deactivated",
    "representative:reactivated": "Sales representative reactivated",
    "representative:paid": "Bonus paid to a representative",
    representative_set: "Representative credited with a shop",
    gifted_for_life: "Licence given for life",
    cancelled: "Licence cancelled",
    extended: "Licence extended",
    banned: "Shop banned",
    unbanned: "Ban lifted",
  },

  staff: {
    title: "Team",
    intro: "The people who can open this admin area. Each signs in with a username, a password, then the six-digit code from their phone.",
    you: "you",
    since: "since {date}",
    factorReady: "authenticator set up",
    factorMissing: "QR code at first sign-in",
    formTitle: "Add someone, or change a password",
    formIntro: "A username already on the team simply gets the new password.",
    login: "Sign-in name",
    loginHint: "What this person will type to sign in: their email address, or any name you choose.",
    name: "Display name (optional)",
    password: "Password",
    passwordHint: "At least 12 characters.",
    again: "The same password",
    save: "Save",
    added: "Done. {login} can sign in to the admin area. The first sign-in shows a QR code: scan it with an authenticator app.",
    passwordSet: "New password saved for {login}.",
    resetFactor: "Lost phone: make a new QR code",
    factorReset: "Done. The next sign-in will show a new QR code.",
    remove: "Remove from the team",
    removeConfirm: "Remove {login}? Their username will no longer open the admin area.",
    removeYes: "Yes, remove",
    removed: "Removed from the team.",
    cancel: "Cancel",
    errors: {
      bad_login: "Write a username, of 100 characters at most.",
      too_short: "The password needs at least 12 characters.",
      only_digits: "The password cannot be only digits.",
      one_character: "The password cannot repeat a single character.",
      mismatch: "The two passwords are not the same.",
      yourself: "You cannot remove yourself.",
      open_preview: "On an open test link the team cannot be changed. Do it from your own computer, or once signed in.",
      failed: "Nothing was saved. Try again.",
    },
  },

  codes: {
    title: "Renewal codes",
    intro:
      "The owner reads you the code his software shows. You read him this one. He types it with no internet and his software starts again.",
    shop: "The shop",
    deviceCode: "The code his software shows",
    newEnd: "New end date",
    generate: "Make the code",
    notGenerated: "Not made.",
    readToOwner: "Read this to the owner",
    copy: "Copy",
    copied: "Copied",
    recent: "Latest codes",
    until: "until {date}",
  },

  funnel: {
    title: "Funnel",
    nobody: "Nobody has started yet.",
    step: "Step",
    reached: "Reached",
    perHundred: "Per hundred",
    steps: ["Your shop", "Questions", "Products and staff", "Serial number"],
    byPack: "By trade",
    byDevice: "Phone or computer",
    noPack: "no trade",
    unknown: "unknown",
  },

  requests: {
    title: "What owners have asked for",
    nothing: "Nothing yet.",
    noPack: "no trade",
    noQuestion: "no question",
    leadsTitle: "Trades that have no software yet",
    noLeads: "Nobody has left their number yet.",
    codesTitle: "Serial numbers to send again",
    codesIntro:
      "Sending on WhatsApp is not connected yet. Send the number by hand with the link, then mark it sent.",
    noCodes: "No requests waiting.",
    expired: "expired",
    sendOnWhatsApp: "Send on WhatsApp",
    markSent: "Mark sent",
    markedSent: "Sent",
    revive: "Revive",
    revived: "Working again for {days} days.",
    reviveTitle: "Revive an expired number",
    reviveLabel: "The number, as the owner sent it",
    reviveFailed: "Number not found.",
    actionFailed: "That did not go through. Try again.",
  },

  settings: {
    title: "Settings",
    intro:
      "Values change here, never in the code. An empty price means the page says so, rather than inventing a figure.",
    testPacks: "Trades in test are closed to customers. This link opens them in this browser, to try them.",
    testBuilder: "Test the builder",
    leaveTest: "Leave test mode",
    save: "Save",
    saved: "Saved",
    notJson: "That is not a valid value. A number is written 15000, text in quotation marks.",
    wrongKind: "This value has to stay the same type as before ({was}).",
    notSaved: "Not saved.",
  },

  aiCost: {
    title: "AI cost",
    none: "No calls yet.",
    total: "{calls} calls, {tokens} tokens in all.",
    outcome: "Outcome",
    calls: "Calls",
    tokens: "Tokens",
  },

  trials: {
    title: "Trials",
    intro:
      "One trial per shop. Nothing flagged below has blocked anyone: it is a reason to look, not an accusation.",
    flagged: "Possible repeat trial ({count})",
    nothingFlagged: "Nothing to flag.",
    unnamed: "Unnamed",
    refused: "Refused, to call back ({count})",
    nobodyRefused: "Nobody.",
    refusedFallback: "Refused",
    grantTitle: "Grant a trial",
    grantIntro:
      "For a second-hand computer, a repaired machine we did not recognise, or anyone we refused wrongly. Their trial starts at their next activation.",
    all: "All trials ({count})",
    shop: "The shop",
    choose: "Choose",
    why: "Why",
    whyExample: "Second-hand computer, checked by phone",
    grant: "Grant a trial",
    granted: "Done. Their trial starts at their next activation.",
    grantFailed: "Nothing was saved. Try again.",
    testEndTitle: "Test the end of the trial",
    testEndIntro:
      "On the test version only. Ends the chosen shop's trial at once: close and reopen the software, connected to the internet, and the end-of-trial window shows, with its serial number and QR code.",
    testEndButton: "End the trial now",
    testEndDone: "Trial ended. Close and reopen the software.",
    testEndNotTrial: "This shop already has a paid licence: nothing was changed.",
    signals: {
      same_logo: "Same logo as an earlier trial",
      same_products: "Same product list",
      similar_name: "Very similar shop name",
      similar_address: "Very similar address",
    },
    refusals: {
      same_machine: "Same computer as an earlier trial",
      same_phone: "Same phone number",
      same_business: "This shop has already had its trial",
      no_fingerprint: "The software sent no machine fingerprint",
    },
  },
};

const ar: AdminCopy = {
  brand: "إدارة OUAQT",
  noDatabase: "لا توجد قاعدة بيانات مهيأة.",
  staffFallback: "الفريق",
  openStaff: "اختبار، دون تسجيل دخول",
  openBanner:
    "إدارة الاختبار، مفتوحة دون تسجيل دخول. تغلق نفسها في الإنتاج وعلى أي قاعدة بيانات أخرى.",

  nav: {
    overview: "نظرة عامة",
    stats: "الإحصائيات",
    payments: "المدفوعات",
    clients: "الزبائن",
    control: "التحكم",
    devices: "الأجهزة",
    codes: "الرموز",
    funnel: "المسار",
    trials: "التجارب",
    requests: "الطلبات",
    settings: "الإعدادات",
    aiCost: "تكلفة الذكاء الاصطناعي",
    staff: "الفريق",
    reps: "المندوبون",
  },

  navGroups: { follow: "المتابعة", setup: "الإعداد" },

  packs: { pharmacy: "صيدلية", bakery: "مخبزة", restaurant: "مطعم", warehouse: "مستودع", shop: "متجر", hotel: "فندق", transport: "نقل", general: "نشاط آخر" },
  plans: {
    trial: "تجربة",
    annual: "سنوية",
    semiannual: "نصف سنوية",
    quarterly: "فصلية",
    perpetual: "دائمة",
    extra_device: "جهاز إضافي",
    setup_visit: "زيارة تثبيت",
  },
  statuses: {
    trial: "تجربة",
    active: "سارية",
    expired_trial: "انتهت التجربة",
    renewal_due: "يلزم التجديد",
    expired: "منتهية",
    suspended: "موقوفة",
  },
  roles: { main: "رئيسي", secondary: "ثانوي" },

  signIn: {
    email: "البريد الإلكتروني أو اسم المستخدم",
    password: "كلمة المرور",
    continue: "متابعة",
    scan: "امسح هذا الرمز بتطبيق مصادقة، ثم اكتب الرمز المكون من ستة أرقام الذي يعرضه.",
    orKey: "أو اكتب هذا المفتاح:",
    checking: "جار التحقق…",
    setupTitle: "أول دخول: اربط هاتفك",
    step1: "ثبت على هاتفك تطبيق مصادقة مجانيا: Google Authenticator أو Microsoft Authenticator أو Authy.",
    step2: "في التطبيق، اضغط «+» ثم «مسح رمز QR»، ووجه الكاميرا إلى هذا الرمز.",
    step3: "يعرض التطبيق OUAQT مع رمز من ستة أرقام يتغير كل 30 ثانية. اكتب الرمز المعروض أدناه.",
    codeHint: "يعرض الرمز تطبيق المصادقة على هاتفك، تحت OUAQT. يتغير كل 30 ثانية.",
    retry: "أعد المحاولة",
    code: "رمز من ستة أرقام",
    signIn: "تسجيل الدخول",
    notStaff: "هذا الحساب ليس في قائمة الفريق. إن كنت صاحب محل، فبرنامجك في حسابك الخاص.",
    signOut: "تسجيل الخروج",
    wrong: "اسم المستخدم أو كلمة المرور غير صحيحة.",
    setupFailed: "تعذر بدء إعداد تطبيق المصادقة.",
    noFactor: "لا يوجد تطبيق مصادقة للتحقق.",
    challengeFailed: "تعذر طلب رمز.",
    badCode: "لم يقبل هذا الرمز.",
  },

  payments: {
    title: "مدفوعات بانتظار التأكيد",
    empty: "لا شيء للتأكيد. تصل المدفوعات هنا بمجرد أن يرسل صاحب محل صورة التحويل.",
    launch: "سعر الانطلاق",
    expected: "المنتظر",
    plan: "الصيغة",
    app: "التطبيق",
    reference: "المرجع",
    none: "لا شيء",
    received: "استلم في",
    readAmount: "المبلغ المقروء",
    readDate: "التاريخ المقروء",
    readRecipient: "أرسل إلى",
    notRead: "لم يقرأ الذكاء الاصطناعي الصورة: اقرأ المبلغ والتاريخ والمرجع في الصورة.",
    screenshotAlt: "صورة التحويل",
    noScreenshot: "الصورة غير موجودة.",
    reasonLabel: "السبب، إن رفضت",
    reasonNeeded: "اذكر السبب: سيراه صاحب المحل.",
    confirm: "تأكيد",
    reject: "رفض",
    confirmed: "تم التأكيد",
    rejected: "مرفوض",
    failed: "لم يسجل.",
    automaticTitle: "مؤكدة تلقائيا، للمراجعة",
    automaticIntro: "قرئت الصورة وتطابق كل شيء، ففتحت الرخصة في الحال. انظر إلى الصورة: أبق الدفعة، أو ألغها إن لم تكن الصورة كما تبدو. الإلغاء يعيد الرخصة كما كانت.",
    keep: "لا بأس",
    kept: "أبقيت",
    undo: "إلغاء الدفعة",
    undoReasonLabel: "السبب، إن ألغيت",
  },

  clients: {
    title: "الزبائن",
    search: "اسم المحل أو الرقم التسلسلي",
    searchButton: "بحث",
    nothingFound: "لم يعثر على شيء.",
    none: "لا يوجد زبائن بعد.",
    noLicence: "دون رخصة",
    launch: "سعر الانطلاق",
    all: "الكل",
    seen: "شوهد {ago}",
    neverSeen: "لم يتصل بعد",
    shown: "{shown} من {total}",
    searchingFor: "نتائج البحث عن «{query}»",
    clearSearch: "مسح البحث",
  },

  devices: {
    title: "الأجهزة",
    none: "لم يفعل أي حاسوب بعد.",
    unnamed: "دون اسم",
    freed: "محرر",
    seen: "آخر ظهور {date}",
    reason: "السبب",
    release: "تحرير",
    reasonNeeded: "اذكر السبب: يبقى مسجلا.",
    notFreed: "لم يحرر.",
  },

  search: {
    placeholder: "ابحث عن زبون: الاسم، الهاتف، الرقم التسلسلي، رمز الجهاز",
    none: "لا يوجد زبون مطابق.",
    all: "عرض كل النتائج ({count})",
    searching: "جار البحث…",
    by: "حسب {what}",
    matched: {
      name: "الاسم",
      phone: "الهاتف",
      serial: "الرقم التسلسلي",
      device: "رمز الجهاز",
      address: "العنوان",
      id: "المعرف",
    },
  },

  overview: {
    title: "نظرة عامة",
    live: "مباشر · {time}",
    refresh: "تحديث",
    allClear: "لا شيء ينتظر ردا.",
    todo: {
      payments: "مدفوعات للتأكيد",
      review: "مدفوعات تلقائية للمراجعة",
      codes: "أرقام تسلسلية لإعادة الإرسال",
      requests: "طلبات من أصحاب المحلات",
    },
    kpi: {
      clients: "الزبائن",
      clientsSub: "+{count} في آخر 7 أيام",
      online: "برامج متصلة",
      onlineSub: "{shops} محلات · {total} حواسيب مفعلة",
      paying: "رخص مدفوعة",
      payingSub: "{amount} محصلة هذا الشهر",
      visitors: "في المنشئ الآن",
      visitorsSub: "{count} اليوم",
      site: "زوار الموقع اليوم",
      siteSub: "{now} الآن · {week} في 7 أيام",
      downloads: "التنزيلات",
      downloadsSub: "{today} اليوم · ويندوز {windows} · ماك {mac}",
    },
    statusTitle: "حالة الزبائن",
    statusTotal: "{count} محلات",
    noLicence: "دون رخصة",
    tiles: {
      total: "المحلات",
      trial: "في التجربة",
      active: "رخصة سارية",
      renewal_due: "يلزم التجديد",
      expired: "منتهية، للقراءة فقط",
      suspended: "موقوفة",
    },
    appsTitle: "البرامج المثبتة",
    appsIntro: "يتصل كل برنامج عند تشغيله، ثم كل 3 ساعات ما دام متصلا بالإنترنت.",
    presence: {
      now: "متصل، أقل من 3 ساعات",
      today: "شوهد في آخر 24 ساعة",
      week: "شوهد في آخر 7 أيام",
      older: "غير نشط منذ أكثر من 7 أيام",
    },
    platforms: "ويندوز {windows} · ماك {mac}",
    activityTitle: "النشاط",
    series: { shops: "زبائن جدد", visitors: "زوار المنشئ", activations: "حواسيب مفعلة" },
    range: { d7: "7 أيام", d30: "30 يوما" },
    periodTotal: "خلال {days} يوما",
    chartEmpty: "لا شيء في هذه الفترة.",
    appsListTitle: "البرامج، الأحدث أولا",
    filters: { now: "متصل", today: "24 ساعة", week: "7 أيام", all: "الكل" },
    noApps: "لا يوجد برنامج في هذه الفترة.",
    endingTitle: "ينتهي خلال 7 أيام",
    endingNone: "لا تنتهي أي تجربة أو رخصة هذا الأسبوع.",
    endsToday: "اليوم",
    endsIn: "{days} ي",
    historyTitle: "آخر الإجراءات",
    historyNone: "لا شيء بعد.",
    automatic: "تلقائي",
    seeAll: "عرض الكل",
    systemTitle: "صحة النظام",
    signingOk: "الرخص توقع.",
    signingMissing: "مفتاح التوقيع غير موجود: لا يمكن لأي برنامج أن يفعل أو يجدد.",
    aiUse: "الذكاء الاصطناعي، 24 ساعة: {used} استدعاء من {limit}.",
    aiNear: "الذكاء الاصطناعي، 24 ساعة: {used} استدعاء من {limit}. بعدها يقرأ شخص الجمل والصور.",
    autoConfirmOn: "المدفوعات التي تطابق صورتها تتأكد وحدها.",
    autoConfirmOff: "كل دفعة تنتظر شخصا.",
    downloads: "التنزيلات: ويندوز {windows}/{total} أنشطة، ماك {mac}/{total}.",
  },

  client: {
    back: "كل الزبائن",
    notFound: "هذا المحل غير موجود، أو لم يعد موجودا.",
    since: "زبون منذ {date}",
    launch: "زبون بسعر الانطلاق",
    contactTitle: "الاتصال",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    noContact: "لا توجد بيانات اتصال.",
    whatsapp: "راسله على واتساب",
    licenceTitle: "الرخصة",
    plan: "الصيغة",
    status: "الحالة",
    starts: "البداية",
    ends: "النهاية",
    noEnd: "دون نهاية",
    notStarted: "تبدأ عند أول تفعيل",
    daysLeft: "الأيام المتبقية: {days}",
    daysLeftShort: "{days} يوما متبقية",
    noLicence: "ليست لهذا المحل رخصة.",
    controlsTitle: "التحكم",
    suspend: "إيقاف البرنامج",
    suspendIntro:
      "عند الإخلال بالشروط. يصبح البرنامج للقراءة فقط عند اتصاله التالي: خلال 3 ساعات على الأكثر إن كان متصلا بالإنترنت، وإلا فور عودة الاتصال. يحتفظ صاحب المحل بكل بياناته ويستطيع قراءتها وتصديرها، وتطلب منه رسالة الاتصال بكم. لا يحذف شيء.",
    suspendReason: "الإخلال، في كلمات قليلة",
    suspendConfirm: "إيقاف {name}",
    suspendedDone: "تم الإيقاف. سيعرف البرنامج ذلك عند اتصاله التالي.",
    reactivate: "إعادة تشغيل البرنامج",
    reactivateIntro: "يعود البرنامج كما كان عند اتصاله التالي، بالتواريخ التي كانت له.",
    reactivateReason: "لماذا الآن",
    reactivateConfirm: "إعادة تشغيل {name}",
    reactivatedDone: "أعيد التشغيل. سيعرف البرنامج ذلك عند اتصاله التالي.",
    grant: "تجديد أو تفعيل",
    setEnd: "تغيير تاريخ النهاية",
    setEndIntro: "لتمديد تجربة، أو منح أيام، أو تصحيح تاريخ. يتبع البرنامج التاريخ الجديد عند اتصاله التالي. التجربة التي لم تبدأ تبدأ اليوم.",
    setEndDate: "تاريخ النهاية الجديد",
    setEndReason: "السبب",
    setEndConfirm: "حفظ التاريخ",
    setEndDone: "تاريخ النهاية الجديد: {date}.",
    end: "إنهاء الاشتراك",
    endIntro: "تنتهي الرخصة اليوم. التجربة تصبح للقراءة فقط في الحال. الرخصة المدفوعة تذكر بالتجديد كل يوم لمدة {grace} يوما، ثم تصبح للقراءة فقط. لإيقاف كل شيء فورا، أوقف البرنامج بدلا من ذلك.",
    endReason: "السبب",
    endConfirm: "إنهاء اشتراك {name}",
    endDone: "ينتهي الاشتراك اليوم. سيعرف البرنامج ذلك عند اتصاله التالي.",
    grantIntro:
      "لدفعة وصلت خارج الموقع، نقدا أو بتحويل. تضاف المدة إلى تاريخ النهاية الحالي. البرنامج الموقوف يبقى موقوفا حتى تعيد تشغيله.",
    grantPlan: "الصيغة",
    grantReason: "كيف دفع",
    grantConfirm: "تفعيل",
    grantedUntil: "سارية حتى {date}.",
    grantedForever: "سارية، دون تاريخ نهاية.",
    reasonNeeded: "اكتب السبب: يبقى في السجل.",
    failed: "لم يتغير شيء. أعد المحاولة.",
    cancel: "إلغاء",
    devicesTitle: "الحواسيب",
    paymentsTitle: "المدفوعات",
    noPayments: "لا توجد مدفوعات.",
    paymentStatuses: {
      submitted: "في الانتظار",
      pending_confirmation: "في الانتظار",
      confirmed: "مؤكدة",
      rejected_auto: "رفضت تلقائيا",
      rejected_manual: "مرفوضة",
    },
    historyTitle: "السجل",
    noHistory: "لا شيء بعد.",
  },

  actions: {
    end_date_set: "غير تاريخ النهاية",
    subscription_ended: "أنهي الاشتراك",
    activated: "فعلت الرخصة",
    confirmed: "أكدت الدفعة",
    confirmed_auto: "أكدت الدفعة تلقائيا",
    rejected_manual: "رفضت الدفعة",
    auto_confirmation_kept: "روجعت دفعة تلقائية",
    auto_confirmation_undone: "ألغيت دفعة تلقائية",
    released_by_owner: "حرر صاحب المحل حاسوبا",
    released_by_staff: "حرر الفريق حاسوبا",
    renewal_code_generated: "أعطي رمز تجديد",
    trial_started: "بدأت التجربة",
    trial_refused: "رفضت التجربة",
    trial_granted_by_hand: "منحت تجربة يدويا",
    trial_ended_for_test: "أنهيت التجربة لاختبار",
    suspended: "أوقف البرنامج",
    suspension_lifted: "أعيد تشغيل البرنامج",
    "device:activated": "فعل حاسوب",
    "device:reactivated": "فعل حاسوب من جديد",
    test_mode_opened: "فتح وضع الاختبار",
    granted_by_hand: "فعلت الرخصة يدويا",
    changed: "عدل إعداد",
    configuration_code_sent_by_hand: "أعيد إرسال الرقم التسلسلي",
    configuration_code_revived: "أعيد تفعيل الرقم التسلسلي",
    staff_added: "أضيف عضو إلى الفريق",
    staff_password_set: "غيرت كلمة مرور عضو",
    staff_factor_reset: "مسح تطبيق المصادقة لعضو",
    staff_removed: "أزيل عضو من الفريق",
    "representative:created": "أضيف مندوب",
    "representative:updated": "عُدّلت مكافأة مندوب",
    "representative:deactivated": "أوقف مندوب",
    "representative:reactivated": "أعيد تفعيل مندوب",
    "representative:paid": "دُفعت مكافأة لمندوب",
    representative_set: "نُسب محل إلى مندوب",
    gifted_for_life: "رخصة ممنوحة مدى الحياة",
    cancelled: "أُلغيت الرخصة",
    extended: "مُدّدت الرخصة",
    banned: "حُظر المحل",
    unbanned: "رُفع الحظر",
  },

  staff: {
    title: "الفريق",
    intro: "الأشخاص الذين يمكنهم فتح هذه الإدارة. يدخل كل واحد باسم المستخدم وكلمة المرور، ثم بالرمز المكون من ستة أرقام من هاتفه.",
    you: "أنت",
    since: "منذ {date}",
    factorReady: "تطبيق المصادقة جاهز",
    factorMissing: "رمز QR عند أول دخول",
    formTitle: "إضافة شخص، أو تغيير كلمة مرور",
    formIntro: "اسم المستخدم الموجود في الفريق يأخذ كلمة المرور الجديدة فقط.",
    login: "اسم الدخول",
    loginHint: "ما سيكتبه هذا الشخص للدخول: بريده الإلكتروني، أو أي اسم تختاره.",
    name: "الاسم الظاهر (اختياري)",
    password: "كلمة المرور",
    passwordHint: "12 حرفا على الأقل.",
    again: "كلمة المرور نفسها",
    save: "حفظ",
    added: "تم. يمكن لـ {login} الدخول إلى الإدارة. يظهر رمز QR عند أول دخول: امسحه بتطبيق مصادقة.",
    passwordSet: "حفظت كلمة المرور الجديدة لـ {login}.",
    resetFactor: "هاتف مفقود: رمز QR جديد",
    factorReset: "تم. سيظهر رمز QR جديد عند الدخول التالي.",
    remove: "إزالة من الفريق",
    removeConfirm: "إزالة {login}؟ لن يفتح اسم المستخدم هذا الإدارة بعد الآن.",
    removeYes: "نعم، إزالة",
    removed: "أزيل من الفريق.",
    cancel: "إلغاء",
    errors: {
      bad_login: "اكتب اسم مستخدم، من 100 حرف على الأكثر.",
      too_short: "يجب أن تتكون كلمة المرور من 12 حرفا على الأقل.",
      only_digits: "لا يمكن أن تكون كلمة المرور أرقاما فقط.",
      one_character: "لا يمكن أن تكرر كلمة المرور حرفا واحدا.",
      mismatch: "كلمتا المرور غير متطابقتين.",
      yourself: "لا يمكنك إزالة نفسك.",
      open_preview: "لا يمكن تغيير الفريق من رابط اختبار مفتوح. افعل ذلك من حاسوبك، أو بعد تسجيل الدخول.",
      failed: "لم يحفظ شيء. أعد المحاولة.",
    },
  },

  codes: {
    title: "رموز التجديد",
    intro:
      "يقرأ لك صاحب المحل الرمز الذي يعرضه برنامجه. وتقرأ له هذا الرمز. فيكتبه دون إنترنت ويعود برنامجه للعمل.",
    shop: "المحل",
    deviceCode: "الرمز الذي يعرضه برنامجه",
    newEnd: "تاريخ الانتهاء الجديد",
    generate: "إنشاء الرمز",
    notGenerated: "لم ينشأ.",
    readToOwner: "اقرأه لصاحب المحل",
    copy: "نسخ",
    copied: "تم النسخ",
    recent: "آخر الرموز",
    until: "حتى {date}",
  },

  funnel: {
    title: "المسار",
    nobody: "لم يبدأ أحد بعد.",
    step: "المرحلة",
    reached: "وصلوا",
    perHundred: "من مئة",
    steps: ["محلك", "الأسئلة", "المنتجات والموظفون", "الرقم التسلسلي"],
    byPack: "حسب النشاط",
    byDevice: "هاتف أو حاسوب",
    noPack: "دون نشاط",
    unknown: "غير معروف",
  },

  requests: {
    title: "ما طلبه أصحاب المحلات",
    nothing: "لا شيء بعد.",
    noPack: "دون نشاط",
    noQuestion: "دون سؤال",
    leadsTitle: "أنشطة ليس لها برنامج بعد",
    noLeads: "لم يترك أحد رقمه بعد.",
    codesTitle: "أرقام تسلسلية يجب إعادة إرسالها",
    codesIntro: "الإرسال على واتساب غير موصول بعد. أرسل الرقم يدويا عبر الرابط، ثم علمه كمرسل.",
    noCodes: "لا توجد طلبات في الانتظار.",
    expired: "منتهي الصلاحية",
    sendOnWhatsApp: "إرسال على واتساب",
    markSent: "تعليم كمرسل",
    markedSent: "أرسل",
    revive: "إعادة التفعيل",
    revived: "يعمل من جديد لمدة {days} يوما.",
    reviveTitle: "إعادة تفعيل رقم منتهي الصلاحية",
    reviveLabel: "الرقم كما أرسله صاحب المحل",
    reviveFailed: "لم نجد هذا الرقم.",
    actionFailed: "لم تتم العملية. أعد المحاولة.",
  },

  settings: {
    title: "الإعدادات",
    intro: "تتغير القيم هنا، لا في الشفرة. السعر الفارغ يعني أن الصفحة تقول ذلك، بدل اختراع رقم.",
    testPacks: "المجالات قيد الاختبار مغلقة أمام الزبائن. هذا الرابط يفتحها في هذا المتصفح لتجربتها.",
    testBuilder: "اختبار المنشئ",
    leaveTest: "الخروج من وضع الاختبار",
    save: "حفظ",
    saved: "تم الحفظ",
    notJson: "هذه ليست قيمة صالحة. يكتب الرقم هكذا 15000، والنص بين علامتي تنصيص.",
    wrongKind: "يجب أن تبقى هذه القيمة من النوع نفسه كما كانت ({was}).",
    notSaved: "لم يحفظ.",
  },

  aiCost: {
    title: "تكلفة الذكاء الاصطناعي",
    none: "لا توجد طلبات بعد.",
    total: "{calls} طلبا، {tokens} وحدة في المجموع.",
    outcome: "النتيجة",
    calls: "الطلبات",
    tokens: "الوحدات",
  },

  trials: {
    title: "التجارب",
    intro: "تجربة واحدة لكل محل. ما يشار إليه أدناه لم يمنع أحدا: إنه سبب للنظر، لا اتهام.",
    flagged: "تجربة مكررة محتملة ({count})",
    nothingFlagged: "لا شيء يستحق الإشارة.",
    unnamed: "دون اسم",
    refused: "مرفوضون، يعاد الاتصال بهم ({count})",
    nobodyRefused: "لا أحد.",
    refusedFallback: "مرفوض",
    grantTitle: "منح تجربة",
    grantIntro:
      "لحاسوب اشتري مستعملا، أو جهاز أصلح ولم نتعرف عليه، أو أي شخص رفضناه خطأ. تبدأ تجربته عند تفعيله القادم.",
    all: "كل التجارب ({count})",
    shop: "المحل",
    choose: "اختر",
    why: "السبب",
    whyExample: "حاسوب مستعمل، تم التحقق بالهاتف",
    grant: "منح تجربة",
    granted: "تم. تبدأ تجربته عند تفعيله القادم.",
    grantFailed: "لم يسجل شيء. أعد المحاولة.",
    testEndTitle: "تجربة نهاية الفترة التجريبية",
    testEndIntro:
      "في نسخة الاختبار فقط. ينهي الفترة التجريبية للمحل المختار فورا: أغلق البرنامج ثم افتحه وهو متصل بالإنترنت، فتظهر نافذة نهاية التجربة برقمه التسلسلي ورمز QR.",
    testEndButton: "إنهاء التجربة الآن",
    testEndDone: "انتهت التجربة. أغلق البرنامج ثم افتحه.",
    testEndNotTrial: "لهذا المحل رخصة مدفوعة: لم يتغير شيء.",
    signals: {
      same_logo: "الشعار نفسه لتجربة سابقة",
      same_products: "قائمة المنتجات نفسها",
      similar_name: "اسم محل قريب جدا",
      similar_address: "عنوان قريب جدا",
    },
    refusals: {
      same_machine: "الحاسوب نفسه لتجربة سابقة",
      same_phone: "رقم الهاتف نفسه",
      same_business: "حصل هذا المحل على تجربته من قبل",
      no_fingerprint: "لم يرسل البرنامج أي بصمة للجهاز",
    },
  },
};

export const adminCopy: Record<AdminLanguage, AdminCopy> = { fr, en, ar };

/*
 * The locale for dates and numbers on staff screens.
 *
 * Arabic uses plain day/month/year digits rather than the Arabic locale's own
 * format. That one puts invisible right-to-left marks between the numbers,
 * and beside a shop name written in Latin letters they tore the date apart:
 * "22 · Pharmacie Essai 2026/9/". Digits stay Western, as everywhere else.
 */
export const adminLocale: Record<AdminLanguage, string> = {
  fr: "fr-FR",
  en: "en-GB",
  ar: "en-GB",
};

/** A stored value in the reader's words, or the value itself when it has none. */
export function wordFor(words: Record<string, string>, value: string | null | undefined): string {
  if (!value) return "";
  return words[value] ?? value;
}
